In [5]:
pip install apache-airflow

^C
Note: you may need to restart the kernel to use updated packages.

In [13]:
from airflow.providers.amazon.aws.hooks.redshift_sql import RedshiftSQLHook

C:\ProgramData\anaconda3\lib\site-packages\airflow\__init__.py:35: RuntimeWarning: Airflow currently can be run on POSIX-compliant Operating Systems. For development, it is regularly tested on fairly modern Linux Distros and recent versions of macOS. On Windows you can run it via WSL2 (Windows Subsystem for Linux 2) or via Linux Containers. The work to add Windows support is tracked via https://github.com/apache/airflow/issues/10388, but it is not a high priority.
  warnings.warn(

AirflowConfigException: Cannot use relative path: `sqlite:///C:\Users\Vrashi/airflow/airflow.db` to connect to sqlite. Please use absolute path such as `sqlite:////tmp/airflow.db`.

In [289]:
import requests
#from airflow.utils.dates import days_ago
import requests
import csv
from datetime import datetime
import pandas as pd
import os
import json

In [290]:
url = 'https://trading-api.tipico.us/v1/pds/lbc/events/live?licenseId=US-NJ&lang=en&limit=18'
response = requests.get(url)
data = response.json()

In [279]:
data

[{'id': 816775,
  'startTime': '2024-05-29T00:00:00Z',
  'messageTime': '2024-05-31T11:00:31.228Z',
  'sportType': 'GOLF',
  'matchState': 'ONGOING',
  'participants': [{'id': 86605,
    'name': 'Hammer, Marc',
    'position': 'OTHER',
    'abbreviation': 'HAM'},
   {'id': 86608,
    'name': 'Friedrichsen, Sebastian',
    'position': 'OTHER',
    'abbreviation': 'FRI'},
   {'id': 86742,
    'name': 'Paul, Yannik',
    'position': 'OTHER',
    'abbreviation': 'PAU'},
   {'id': 86743,
    'name': 'McKibbin, Tom',
    'position': 'OTHER',
    'abbreviation': 'MCK'},
   {'id': 3324,
    'name': 'Wiesberger, Bernd',
    'position': 'OTHER',
    'abbreviation': 'WIE'},
   {'id': 86549,
    'name': 'Lawrence, Thriston',
    'position': 'OTHER',
    'abbreviation': 'LAW'},
   {'id': 86615,
    'name': 'Schott, Freddy',
    'position': 'OTHER',
    'abbreviation': 'SCH'},
   {'id': 86554,
    'name': 'Forsstrom, Simon',
    'position': 'OTHER',
    'abbreviation': 'FOR'},
   {'id': 86623,
    'name': 'Tillmanns, Tim',
    'position': 'OTHER',
    'abbreviation': 'TIL'},
   {'id': 8138,
    'name': 'Hill, Callum',
    'position': 'OTHER',
    'abbreviation': 'HIL'},
   {'id': 3418,
    'name': 'Lorenzo-Vera, Michael',
    'position': 'OTHER',
    'abbreviation': 'LOR'},
   {'id': 8023,
    'name': 'Hillier, Daniel',
    'position': 'OTHER',
    'abbreviation': 'HIL'},
   {'id': 86531,
    'name': 'Siem, Marcel',
    'position': 'OTHER',
    'abbreviation': 'SIE'},
   {'id': 86558,
    'name': 'Brown, Daniel',
    'position': 'OTHER',
    'abbreviation': 'BRO'},
   {'id': 86595,
    'name': 'Nakajima, Keita',
    'position': 'OTHER',
    'abbreviation': 'NAK'},
   {'id': 86599,
    'name': 'Barron, Haydn',
    'position': 'OTHER',
    'abbreviation': 'BAR'},
   {'id': 86612,
    'name': 'Jones, Sam',
    'position': 'OTHER',
    'abbreviation': 'JON'},
   {'id': 86603,
    'name': 'Helligkilde, Marcus',
    'position': 'OTHER',
    'abbreviation': 'HEL'},
   {'id': 7604,
    'name': 'Wu, Ashun',
    'position': 'OTHER',
    'abbreviation': 'ASH'},
   {'id': 86564,
    'name': 'Veerman, Johannes',
    'position': 'OTHER',
    'abbreviation': 'VEE'},
   {'id': 86566,
    'name': 'Van Driel, Darius',
    'position': 'OTHER',
    'abbreviation': 'VAN'},
   {'id': 86596,
    'name': 'Enefer, William',
    'position': 'OTHER',
    'abbreviation': 'ENE'},
   {'id': 8101,
    'name': 'Kieffer, Maximilian',
    'position': 'OTHER',
    'abbreviation': 'KIE'},
   {'id': 86550,
    'name': 'Gouveia, Ricardo',
    'position': 'OTHER',
    'abbreviation': 'GOU'},
   {'id': 8103,
    'name': 'Jamieson, Scott',
    'position': 'OTHER',
    'abbreviation': 'JAM'},
   {'id': 86581,
    'name': 'Del Rey, Alejandro',
    'position': 'OTHER',
    'abbreviation': 'DEL'},
   {'id': 86626,
    'name': 'Weber, Jordan',
    'position': 'OTHER',
    'abbreviation': 'WEB'},
   {'id': 7609,
    'name': 'Law, David',
    'position': 'OTHER',
    'abbreviation': 'LAW'},
   {'id': 8112,
    'name': 'Otaegui, Adrian',
    'position': 'OTHER',
    'abbreviation': 'OTA'},
   {'id': 86532,
    'name': 'Fichardt, Darren',
    'position': 'OTHER',
    'abbreviation': 'FIC'},
   {'id': 86611,
    'name': 'Jarvis, Casey',
    'position': 'OTHER',
    'abbreviation': 'JAR'},
   {'id': 86573,
    'name': 'Hanna, Chase',
    'position': 'OTHER',
    'abbreviation': 'HAN'},
   {'id': 8091,
    'name': 'Wilson, Oliver',
    'position': 'OTHER',
    'abbreviation': 'WIL'},
   {'id': 86571,
    'name': 'Ruuska, Lauri',
    'position': 'OTHER',
    'abbreviation': 'RUU'},
   {'id': 86746,
    'name': 'Bachem, Nick',
    'position': 'OTHER',
    'abbreviation': 'BAC'},
   {'id': 86559,
    'name': 'Sordet, Clement',
    'position': 'OTHER',
    'abbreviation': 'SOR'},
   {'id': 8260,
    'name': 'Syme, Connor',
    'position': 'OTHER',
    'abbreviation': 'SYM'},
   {'id': 3597,
    'name': 'Southgate, Matthew',
    'position': 'OTHER',
    'abbreviation': 'SOU'},
   {'id': 8140,
    'name': 'Arnaus, Adri',
    'position': 'OTHER',
    'abbreviation': 'ARN'},
   {'id': 86553,
    'name': 'Cantero Gutierrez, Ivan',
    'position': 'OTHER',
    'abbreviation': 'CAN'},
   {'id': 3596,
    'name': 'Pepperell, Eddie',
    'position': 'OTHER',
    'abbreviation': 'PEP'},
   {'id': 3374,
    'name': 'Hojgaard, Rasmus',
    'position': 'OTHER',
    'abbreviation': 'HOJ'},
   {'id': 86600,
    'name': 'Elvira, Manuel',
    'position': 'OTHER',
    'abbreviation': 'ELV'},
   {'id': 86546,
    'name': 'Porteous, Garrick',
    'position': 'OTHER',
    'abbreviation': 'POR'},
   {'id': 86555,
    'name': 'Girrbach, Joel',
    'position': 'OTHER',
    'abbreviation': 'GIR'},
   {'id': 86618,
    'name': 'Bairstow, Sam',
    'position': 'OTHER',
    'abbreviation': 'BAI'},
   {'id': 8124,
    'name': 'Winther, Jeff',
    'position': 'OTHER',
    'abbreviation': 'WIN'},
   {'id': 86543,
    'name': 'Kofstad, Espen',
    'position': 'OTHER',
    'abbreviation': 'KOF'},
   {'id': 86536,
    'name': 'Nemecz, Lukas',
    'position': 'OTHER',
    'abbreviation': 'NEM'},
   {'id': 86748,
    'name': 'Katsuragawa, Yuto',
    'position': 'OTHER',
    'abbreviation': 'KAT'},
   {'id': 86602,
    'name': 'Ko, Jeong Weon',
    'position': 'OTHER',
    'abbreviation': 'JEO'},
   {'id': 8137,
    'name': 'Rozner, Antoine',
    'position': 'OTHER',
    'abbreviation': 'ROZ'},
   {'id': 86613,
    'name': 'Neergaard-Petersen, Rasmus',
    'position': 'OTHER',
    'abbreviation': 'NEE'},
   {'id': 86597,
    'name': 'Mansell, Richard',
    'position': 'OTHER',
    'abbreviation': 'MAN'},
   {'id': 86580,
    'name': 'Rugumayo, Ronald',
    'position': 'OTHER',
    'abbreviation': 'RUG'},
   {'id': 8129,
    'name': 'Sharma, Shubhankar',
    'position': 'OTHER',
    'abbreviation': 'SHA'},
   {'id': 8080,
    'name': 'Colsaerts, Nicolas',
    'position': 'OTHER',
    'abbreviation': 'COL'},
   {'id': 75131,
    'name': 'Goth-Rasmussen, Jonathan',
    'position': 'OTHER',
    'abbreviation': 'GOT'},
   {'id': 3584,
    'name': 'Pavan, Andrea',
    'position': 'OTHER',
    'abbreviation': 'PAV'},
   {'id': 86533,
    'name': 'Manley, Stuart',
    'position': 'OTHER',
    'abbreviation': 'MAN'},
   {'id': 3349,
    'name': 'Sullivan, Andy',
    'position': 'OTHER',
    'abbreviation': 'SUL'},
   {'id': 7595,
    'name': 'Kjeldsen, Soren',
    'position': 'OTHER',
    'abbreviation': 'KJE'},
   {'id': 3346,
    'name': 'Schwab, Matthias',
    'position': 'OTHER',
    'abbreviation': 'SCH'},
   {'id': 7599,
    'name': 'Guerrier, Julien',
    'position': 'OTHER',
    'abbreviation': 'GUE'},
   {'id': 3419,
    'name': 'Frittelli, Dylan',
    'position': 'OTHER',
    'abbreviation': 'FRI'},
   {'id': 3600,
    'name': 'Armitage, Marcus',
    'position': 'OTHER',
    'abbreviation': 'ARM'},
   {'id': 86535,
    'name': 'Figueiredo, Pedro',
    'position': 'OTHER',
    'abbreviation': 'FIG'},
   {'id': 86587,
    'name': 'Lacroix, Frederic',
    'position': 'OTHER',
    'abbreviation': 'LAC'},
   {'id': 86557,
    'name': 'Garcia Rodriguez, Sebastian',
    'position': 'OTHER',
    'abbreviation': 'GAR'},
   {'id': 86562,
    'name': 'Kruyswijk, Jacques',
    'position': 'OTHER',
    'abbreviation': 'KRU'},
   {'id': 86604,
    'name': 'Besard, Matthis',
    'position': 'OTHER',
    'abbreviation': 'BES'},
   {'id': 8106,
    'name': 'Kawamura, Masahiro',
    'position': 'OTHER',
    'abbreviation': 'KAW'},
   {'id': 8098,
    'name': 'Larrazabal, Pablo',
    'position': 'OTHER',
    'abbreviation': 'LAR'},
   {'id': 86575,
    'name': 'Davidson, Jack',
    'position': 'OTHER',
    'abbreviation': 'DAV'},
   {'id': 86609,
    'name': 'Ravetto, David',
    'position': 'OTHER',
    'abbreviation': 'RAV'},
   {'id': 86584,
    'name': 'Moolman, Pieter',
    'position': 'OTHER',
    'abbreviation': 'MOO'},
   {'id': 86620,
    'name': 'Vaillant, Tom',
    'position': 'OTHER',
    'abbreviation': 'VAI'},
   {'id': 86551,
    'name': 'Chouhan, Om Prakash',
    'position': 'OTHER',
    'abbreviation': 'CHO'},
   {'id': 8033,
    'name': 'Chen, Guxin',
    'position': 'OTHER',
    'abbreviation': 'CHE'},
   {'id': 86610,
    'name': 'Nicholas, James',
    'position': 'OTHER',
    'abbreviation': 'NIC'},
   {'id': 86534,
    'name': 'Garcia-Heredia, Alfredo',
    'position': 'OTHER',
    'abbreviation': 'GAR'},
   {'id': 3598,
    'name': 'Langasque, Romain',
    'position': 'OTHER',
    'abbreviation': 'LAN'},
   {'id': 86552,
    'name': 'Schneider, Marcel',
    'position': 'OTHER',
    'abbreviation': 'SCH'},
   {'id': 86592,
    'name': 'Wilson, Andrew',
    'position': 'OTHER',
    'abbreviation': 'WIL'},
   {'id': 86590,
    'name': 'Svensson, Jesper',
    'position': 'OTHER',
    'abbreviation': 'SVE'},
   {'id': 86589,
    'name': 'Blomme, Adam',
    'position': 'OTHER',
    'abbreviation': 'BLO'},
   {'id': 3333,
    'name': 'Willett, Daniel',
    'position': 'OTHER',
    'abbreviation': 'WIL'},
   {'id': 86542,
    'name': 'Baldwin, Matthew',
    'position': 'OTHER',
    'abbreviation': 'BAL'},
   {'id': 8134,
    'name': 'Smith, Jordan',
    'position': 'OTHER',
    'abbreviation': 'SMI'},
   {'id': 8008,
    'name': 'Micheluzzi, David',
    'position': 'OTHER',
    'abbreviation': 'MIC'},
   {'id': 3594,
    'name': 'Johnston, Andrew',
    'position': 'OTHER',
    'abbreviation': 'JOH'},
   {'id': 86625,
    'name': 'Broholt Lind, Soren',
    'position': 'OTHER',
    'abbreviation': 'BRO'},
   {'id': 86619,
    'name': 'Kennedy, Frank',
    'position': 'OTHER',
    'abbreviation': 'KEN'},
   {'id': 8131,
    'name': 'Crocker, Sean',
    'position': 'OTHER',
    'abbreviation': 'CRO'},
   {'id': 86578,
    'name': 'Ahlawat, Veer',
    'position': 'OTHER',
    'abbreviation': 'AHL'},
   {'id': 86569,
    'name': 'Von Dellingshausen, Nicolai',
    'position': 'OTHER',
    'abbreviation': 'VON'},
   {'id': 86747,
    'name': 'Ferguson, Ewen',
    'position': 'OTHER',
    'abbreviation': 'FER'},
   {'id': 86622,
    'name': 'Albers, Anton',
    'position': 'OTHER',
    'abbreviation': 'ALB'},
   {'id': 8133,
    'name': 'Shinkwin, Callum',
    'position': 'OTHER',
    'abbreviation': 'SHI'},
   {'id': 86540,
    'name': 'Strydom, Ockie',
    'position': 'OTHER',
    'abbreviation': 'STR'},
   {'id': 86583,
    'name': 'Tarrio, Santiago',
    'position': 'OTHER',
    'abbreviation': 'TAR'},
   {'id': 8102,
    'name': 'Scrivener, Jason',
    'position': 'OTHER',
    'abbreviation': 'SCR'},
   {'id': 3588,
    'name': 'Aphinbarnrat, Kiradech',
    'position': 'OTHER',
    'abbreviation': 'APH'},
   {'id': 86539,
    'name': 'Dantorp, Jens',
    'position': 'OTHER',
    'abbreviation': 'DAN'},
   {'id': 86579,
    'name': 'Coussaud, Ugo',
    'position': 'OTHER',
    'abbreviation': 'COU'},
   {'id': 86561,
    'name': 'Rottluff, Maximilian',
    'position': 'OTHER',
    'abbreviation': 'ROT'},
   {'id': 3605,
    'name': 'Galletti, Nicolo',
    'position': 'OTHER',
    'abbreviation': 'GAL'},
   {'id': 86560,
    'name': 'Scalise, Lorenzo',
    'position': 'OTHER',
    'abbreviation': 'SCA'},
   {'id': 8120,
    'name': 'Stone, Brandon',
    'position': 'OTHER',
    'abbreviation': 'STO'},
   {'id': 8126,
    'name': 'Paratore, Renato',
    'position': 'OTHER',
    'abbreviation': 'PAR'},
   {'id': 7610,
    'name': 'Forrest, Grant',
    'position': 'OTHER',
    'abbreviation': 'FOR'},
   {'id': 86541,
    'name': 'Blixt, Jonas',
    'position': 'OTHER',
    'abbreviation': 'BLI'},
   {'id': 86744,
    'name': 'Long, Hurly',
    'position': 'OTHER',
    'abbreviation': 'LON'},
   {'id': 8094,
    'name': 'Korhonen, Mikko',
    'position': 'OTHER',
    'abbreviation': 'KOR'},
   {'id': 86545,
    'name': 'Saddier, Adrien',
    'position': 'OTHER',
    'abbreviation': 'SAD'},
   {'id': 86591,
    'name': 'Wiebe, Gunner',
    'position': 'OTHER',
    'abbreviation': 'WIE'},
   {'id': 86574,
    'name': 'Gumberg, Jordan',
    'position': 'OTHER',
    'abbreviation': 'GUM'},
   {'id': 86598,
    'name': 'Penge, Marco',
    'position': 'OTHER',
    'abbreviation': 'PEN'},
   {'id': 8114,
    'name': 'Laporta, Francesco',
    'position': 'OTHER',
    'abbreviation': 'LAP'},
   {'id': 86582,
    'name': 'Hidalgo, Angel',
    'position': 'OTHER',
    'abbreviation': 'HID'},
   {'id': 8132,
    'name': 'Migliozzi, Guido',
    'position': 'OTHER',
    'abbreviation': 'MIG'},
   {'id': 86577,
    'name': 'Clements, Todd',
    'position': 'OTHER',
    'abbreviation': 'CLE'},
   {'id': 8092,
    'name': 'Fisher, Ross',
    'position': 'OTHER',
    'abbreviation': 'FIS'},
   {'id': 8099,
    'name': 'Zanotti, Fabrizio',
    'position': 'OTHER',
    'abbreviation': 'ZAN'},
   {'id': 86607,
    'name': 'Christensen, Tiger',
    'position': 'OTHER',
    'abbreviation': 'CHR'},
   {'id': 8111,
    'name': 'Canter, Laurie',
    'position': 'OTHER',
    'abbreviation': 'CAN'},
   {'id': 8107,
    'name': 'Green, Gavin Kyle',
    'position': 'OTHER',
    'abbreviation': 'GRE'},
   {'id': 86556,
    'name': 'Mruzek, Filip',
    'position': 'OTHER',
    'abbreviation': 'MRU'},
   {'id': 8119,
    'name': 'Broberg, Kristoffer',
    'position': 'OTHER',
    'abbreviation': 'BRO'},
   {'id': 86537,
    'name': 'Whitnell, Dale',
    'position': 'OTHER',
    'abbreviation': 'WHI'},
   {'id': 86570,
    'name': 'Moeller, Niklas Noergaard',
    'position': 'OTHER',
    'abbreviation': 'MOE'},
   {'id': 8085,
    'name': 'McEvoy, Richard',
    'position': 'OTHER',
    'abbreviation': 'MCE'},
   {'id': 86616,
    'name': 'De Bruyn, Jannik',
    'position': 'OTHER',
    'abbreviation': 'DE'},
   {'id': 86624,
    'name': 'Siemens, Carl',
    'position': 'OTHER',
    'abbreviation': 'SIE'},
   {'id': 8264,
    'name': 'Schaper, Jayden Trey',
    'position': 'OTHER',
    'abbreviation': 'SCH'},
   {'id': 86614,
    'name': 'Berry, Joshua',
    'position': 'OTHER',
    'abbreviation': 'BER'},
   {'id': 86606,
    'name': 'Bradbury, Daniel',
    'position': 'OTHER',
    'abbreviation': 'BRA'},
   {'id': 86621,
    'name': 'Schutz, Yannick',
    'position': 'OTHER',
    'abbreviation': 'SCH'},
   {'id': 86538,
    'name': 'De Jager, Louis',
    'position': 'OTHER',
    'abbreviation': 'DE'},
   {'id': 8082,
    'name': 'Donaldson, Jamie',
    'position': 'OTHER',
    'abbreviation': 'DON'},
   {'id': 3586,
    'name': 'Waring, Paul',
    'position': 'OTHER',
    'abbreviation': 'WAR'},
   {'id': 86547,
    'name': 'Huizing, Daan',
    'position': 'OTHER',
    'abbreviation': 'HUI'},
   {'id': 3348,
    'name': 'Lewis, Tom',
    'position': 'OTHER',
    'abbreviation': 'LEW'},
   {'id': 3427,
    'name': 'Li, Haotong',
    'position': 'OTHER',
    'abbreviation': 'LIH'},
   {'id': 8130,
    'name': 'Elvira, Nacho',
    'position': 'OTHER',
    'abbreviation': 'ELV'},
   {'id': 86601,
    'name': 'Celli, Filippo',
    'position': 'OTHER',
    'abbreviation': 'CEL'},
   {'id': 8127,
    'name': 'Lombard, Zander',
    'position': 'OTHER',
    'abbreviation': 'LOM'},
   {'id': 86544,
    'name': 'Enoch, Rhys',
    'position': 'OTHER',
    'abbreviation': 'ENO'},
   {'id': 86568,
    'name': 'Johannessen, Kristian Krogh',
    'position': 'OTHER',
    'abbreviation': 'JOH'},
   {'id': 86576,
    'name': 'Williams, Robin',
    'position': 'OTHER',
    'abbreviation': 'WIL'},
   {'id': 86593,
    'name': 'Jordan, Matthew',
    'position': 'OTHER',
    'abbreviation': 'JOR'},
   {'id': 86745,
    'name': 'Fitzpatrick, Alex',
    'position': 'OTHER',
    'abbreviation': 'FIT'},
   {'id': 86572,
    'name': 'Dean, Joe',
    'position': 'OTHER',
    'abbreviation': 'DEA'},
   {'id': 3310,
    'name': 'Cabrera Bello, Rafael',
    'position': 'OTHER',
    'abbreviation': 'CAB'},
   {'id': 7596,
    'name': 'Molinari, Edoardo',
    'position': 'OTHER',
    'abbreviation': 'MOL'},
   {'id': 86548,
    'name': 'Rusch, Benjamin',
    'position': 'OTHER',
    'abbreviation': 'RUS'},
   {'id': 86567,
    'name': 'Prinsloo, Jaco',
    'position': 'OTHER',
    'abbreviation': 'PRI'}],
  'status': 'RUNNING',
  'marketCount': 1,
  'group': {'id': 9041,
   'name': 'European Open (DP World Tour)',
   'parentGroup': {'id': 269,
    'name': 'Men',
    'parentGroup': {'id': 270, 'name': 'Golf'}}},
  'markets': [{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666',
    'name': 'Tournament Winner',
    'type': 'winner',
    'parameters': [],
    'status': 'OPEN',
    'mostBalancedLine': False,
    'sgpEligable': False,
    'outcomes': [{'id': 'c9eef81b-dd18-3077-bba8-2c3106661df7',
      'name': 'Canter, Laurie',
      'isTraded': True,
      'formatDecimal': 7.5,
      'formatAmerican': '650',
      'status': 'ONGOING',
      'trueOdds': 7.5},
     {'id': 'e53af6fa-7048-3c6c-bd83-dc1dd1855a31',
      'name': 'Moeller, Niklas Noergaard',
      'isTraded': True,
      'formatDecimal': 7.75,
      'formatAmerican': '675',
      'status': 'ONGOING',
      'trueOdds': 7.75},
     {'id': '5ffde8f9-fa13-39a3-b221-469ef3fae2db',
      'name': 'McKibbin, Tom',
      'isTraded': True,
      'formatDecimal': 11.75,
      'formatAmerican': '1075',
      'status': 'ONGOING',
      'trueOdds': 11.75},
     {'id': '46a3966f-1122-3eba-a3b3-3d774bfb0227',
      'name': 'Nakajima, Keita',
      'isTraded': True,
      'formatDecimal': 11.75,
      'formatAmerican': '1075',
      'status': 'ONGOING',
      'trueOdds': 11.75},
     {'id': '863e0a64-0424-3092-a4aa-bc4e9f047dfe',
      'name': 'De Bruyn, Jannik',
      'isTraded': True,
      'formatDecimal': 11.75,
      'formatAmerican': '1075',
      'status': 'ONGOING',
      'trueOdds': 11.75},
     {'id': 'edbe572b-4075-34e4-a4a8-66cd880be5de',
      'name': 'Wiesberger, Bernd',
      'isTraded': True,
      'formatDecimal': 14.25,
      'formatAmerican': '1325',
      'status': 'ONGOING',
      'trueOdds': 14.25},
     {'id': 'a895a607-3167-371d-8d60-b1ce872837f0',
      'name': 'Helligkilde, Marcus',
      'isTraded': True,
      'formatDecimal': 18.75,
      'formatAmerican': '1775',
      'status': 'ONGOING',
      'trueOdds': 18.75},
     {'id': '898b68d1-375e-35aa-bf54-a4bc1cbe21be',
      'name': 'Mansell, Richard',
      'isTraded': True,
      'formatDecimal': 19.25,
      'formatAmerican': '1825',
      'status': 'ONGOING',
      'trueOdds': 19.25},
     {'id': '7a6be19e-d3e6-3a6b-b221-b52c542c82fc',
      'name': 'Veerman, Johannes',
      'isTraded': True,
      'formatDecimal': 21.0,
      'formatAmerican': '2000',
      'status': 'ONGOING',
      'trueOdds': 21.0},
     {'id': 'b5500ecb-1c06-3ff2-969b-a2f8a1587426',
      'name': 'Lacroix, Frederic',
      'isTraded': True,
      'formatDecimal': 24.0,
      'formatAmerican': '2300',
      'status': 'ONGOING',
      'trueOdds': 24.0},
     {'id': '3934ea97-b714-37fc-bc46-a02c564e5985',
      'name': 'Crocker, Sean',
      'isTraded': True,
      'formatDecimal': 24.0,
      'formatAmerican': '2300',
      'status': 'ONGOING',
      'trueOdds': 24.0},
     {'id': 'e2bb26e0-cfa0-388e-bb96-4c2c49a88a88',
      'name': 'Migliozzi, Guido',
      'isTraded': True,
      'formatDecimal': 27.0,
      'formatAmerican': '2600',
      'status': 'ONGOING',
      'trueOdds': 27.0},
     {'id': '61ef2909-fcd1-371d-9768-9f7997bc48a2',
      'name': 'Bradbury, Daniel',
      'isTraded': True,
      'formatDecimal': 29.0,
      'formatAmerican': '2800',
      'status': 'ONGOING',
      'trueOdds': 29.0},
     {'id': '38190f36-eced-30a0-a8ac-a0b369cee78f',
      'name': 'Larrazabal, Pablo',
      'isTraded': True,
      'formatDecimal': 33.0,
      'formatAmerican': '3200',
      'status': 'ONGOING',
      'trueOdds': 33.0},
     {'id': 'e7c4bafb-0cb9-34b8-9108-300092f9ffb1',
      'name': 'Schaper, Jayden Trey',
      'isTraded': True,
      'formatDecimal': 41.0,
      'formatAmerican': '4000',
      'status': 'ONGOING',
      'trueOdds': 41.0},
     {'id': 'c1753d5e-6d5a-313c-beec-b708747d8659',
      'name': 'Jordan, Matthew',
      'isTraded': True,
      'formatDecimal': 46.0,

In [291]:
df = pd.DataFrame(data)

In [281]:
df.describe()

                  id  marketCount  updatesCount
count      18.000000    18.000000     18.000000
mean   817634.388889    11.111111    513.666667
std      1656.208006     7.917879    293.088222
min    814872.000000     1.000000     39.000000
25%    816775.250000     5.250000    296.750000
50%    818641.500000     9.000000    510.500000
75%    818803.500000    16.000000    768.250000
max    819147.000000    26.000000    939.000000

In [282]:
df.head()

,id,startTime,messageTime,sportType,matchState,participants,status,marketCount,group,markets,...,eventReferences,eventName,eventDetails,lastModifiedTime,eventTags,score,gameClock,sportCurrentGameState,eventMetadata,aggregatedEventPoints
0,816775,2024-05-29T00:00:00Z,2024-05-31T11:00:31.228Z,GOLF,ONGOING,"[{'id': 86605, 'name': 'Hammer, Marc', 'positi...",RUNNING,1,"{'id': 9041, 'name': 'European Open (DP World ...",[{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666'...,...,"[{'providerId': '49', 'eventId': '23079'}, {'p...",European Open,"{'block_cashout': 'false', 'longTermEventType'...",2024-05-31T11:00:31.356Z,"[blockedOutright, venueStateLocation:UNKNOWN, ...",NaN,NaN,NaN,NaN,NaN
1,814918,2024-05-29T09:05:00Z,2024-05-31T04:03:25.706Z,TENNIS,INTERRUPTED,"[{'id': 86144, 'name': 'Jacquemot E / Tan H', ...",RUNNING,1,"{'id': 54, 'name': 'French Open Women Doubles'...",[{'id': 'c094645a-d6d3-3c59-bed9-0a0449f146b4'...,...,"[{'providerId': '81', 'eventId': '537785798578...",NaN,{'subgroupNameKey': 'French Open Women Doubles...,2024-05-31T04:03:25.837Z,"[awayParticipantStateLocation:UNKNOWN, venueSt...","{'total': {'home': {'sets': 0, 'games': 5, 'po...","{'clockType': 'SECTIONS', 'eventState': 'INTER...","{'updatedAt': '0', 'netSportCurrentGameState':...",NaN,NaN
2,814933,2024-05-29T09:10:00Z,2024-05-31T04:03:18.792Z,TENNIS,INTERRUPTED,"[{'id': 78469, 'name': 'Dolehide CA / Krawczyk...",RUNNING,1,"{'id': 54, 'name': 'French Open Women Doubles'...",[{'id': 'a9bcf7d2-3489-3135-b0d6-a39c20246b59'...,...,"[{'providerId': '81', 'eventId': '537785794342...",NaN,{'subgroupNameKey': 'French Open Women Doubles...,2024-05-31T04:03:18.936Z,"[awayParticipantStateLocation:UNKNOWN, venueSt...","{'total': {'home': {'sets': 1, 'games': 3, 'po...","{'clockType': 'SECTIONS', 'eventState': 'INTER...","{'updatedAt': '0', 'netSportCurrentGameState':...",NaN,NaN
3,814872,2024-05-29T09:15:00Z,2024-05-31T11:01:43.476Z,TENNIS,ONGOING,"[{'id': 94, 'name': 'Koolhof W / Mektic N', 'p...",RUNNING,13,"{'id': 14, 'name': 'French Open Men Doubles', ...",[{'id': 'c84c6a3b-dfd4-3f8d-ae8b-ac993cf19604'...,...,"[{'providerId': '81', 'eventId': '537759095111...",NaN,"{'subgroupNameKey': 'French Open Men Doubles, ...",2024-05-31T11:01:43.613Z,"[awayParticipantStateLocation:UNKNOWN, venueSt...","{'total': {'home': {'sets': 1, 'games': 2, 'po...","{'clockType': 'SECTIONS', 'eventState': 'RUNNI...","{'updatedAt': '0', 'netSportCurrentGameState':...",NaN,NaN
4,816776,2024-05-30T00:00:00Z,2024-05-31T10:59:20.884Z,GOLF,ONGOING,"[{'id': 30935, 'name': 'Du Toit, Jared', 'posi...",RUNNING,1,"{'id': 9036, 'name': 'RBC Canadian Open (PGA T...",[{'id': '0ebe142a-b79f-3b5b-a9bd-ddc589c809de'...,...,"[{'providerId': '49', 'eventId': '23081'}, {'p...",RBC Canadian Open,"{'block_cashout': 'false', 'longTermEventType'...",2024-05-31T10:59:21.012Z,"[blockedOutright, venueStateLocation:UNKNOWN, ...",NaN,NaN,NaN,NaN,NaN

In [143]:
df

,id,startTime,messageTime,sportType,matchState,participants,status,marketCount,group,markets,...,eventReferences,eventName,eventDetails,lastModifiedTime,eventTags,score,gameClock,sportCurrentGameState,eventMetadata,aggregatedEventPoints
0,816775,2024-05-29T00:00:00Z,2024-05-30T23:03:59.822Z,GOLF,ONGOING,"[{'id': 8098, 'name': 'Larrazabal, Pablo', 'po...",RUNNING,1,"{'id': 9041, 'name': 'European Open (DP World ...",[{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666'...,...,"[{'providerId': '49', 'eventId': '23079'}, {'p...",European Open,"{'block_cashout': 'false', 'longTermEventType'...",2024-05-30T23:03:59.951Z,"[blockedOutright, venueStateLocation:UNKNOWN, ...",NaN,NaN,NaN,NaN,NaN
1,814989,2024-05-29T09:00:00Z,2024-05-30T20:32:20.696Z,TENNIS,INTERRUPTED,"[{'id': 71233, 'name': 'Kato M / Kichenok N', ...",RUNNING,1,"{'id': 54, 'name': 'French Open Women Doubles'...",[{'id': 'a85a5cf8-6f94-3d07-baa4-d44f48fc0e9d'...,...,"[{'providerId': '81', 'eventId': '538298978635...",NaN,{'subgroupNameKey': 'French Open Women Doubles...,2024-05-30T20:32:20.840Z,"[awayParticipantStateLocation:UNKNOWN, venueSt...","{'total': {'home': {'sets': 0, 'games': 5, 'po...","{'clockType': 'SECTIONS', 'eventState': 'INTER...","{'updatedAt': '0', 'netSportCurrentGameState':...",NaN,NaN
2,814918,2024-05-29T09:05:00Z,2024-05-30T23:07:01.918Z,TENNIS,INTERRUPTED,"[{'id': 86144, 'name': 'Jacquemot E / Tan H', ...",RUNNING,1,"{'id': 54, 'name': 'French Open Women Doubles'...",[{'id': 'c094645a-d6d3-3c59-bed9-0a0449f146b4'...,...,"[{'providerId': '81', 'eventId': '537785798578...",NaN,{'subgroupNameKey': 'French Open Women Doubles...,2024-05-30T23:07:02.054Z,"[awayParticipantStateLocation:UNKNOWN, venueSt...","{'total': {'home': {'sets': 0, 'games': 5, 'po...","{'clockType': 'SECTIONS', 'eventState': 'INTER...","{'updatedAt': '0', 'netSportCurrentGameState':...",NaN,NaN
3,814870,2024-05-29T09:10:00Z,2024-05-30T20:30:02.262Z,TENNIS,INTERRUPTED,"[{'id': 38216, 'name': 'Johnson L / Mansouri S...",RUNNING,1,"{'id': 14, 'name': 'French Open Men Doubles', ...",[{'id': 'a2ca142e-3dd2-3090-9c13-35807223bcc3'...,...,"[{'providerId': '81', 'eventId': '537759123895...",NaN,"{'subgroupNameKey': 'French Open Men Doubles, ...",2024-05-30T20:30:02.396Z,"[awayParticipantStateLocation:UNKNOWN, venueSt...","{'total': {'home': {'sets': 1, 'games': 1, 'po...","{'clockType': 'SECTIONS', 'eventState': 'INTER...","{'updatedAt': '0', 'netSportCurrentGameState':...",NaN,NaN
4,814933,2024-05-29T09:10:00Z,2024-05-30T23:06:58.779Z,TENNIS,INTERRUPTED,"[{'id': 78469, 'name': 'Dolehide CA / Krawczyk...",RUNNING,1,"{'id': 54, 'name': 'French Open Women Doubles'...",[{'id': 'a9bcf7d2-3489-3135-b0d6-a39c20246b59'...,...,"[{'providerId': '81', 'eventId': '537785794342...",NaN,{'subgroupNameKey': 'French Open Women Doubles...,2024-05-30T23:06:58.914Z,"[awayParticipantStateLocation:UNKNOWN, venueSt...","{'total': {'home': {'sets': 1, 'games': 3, 'po...","{'clockType': 'SECTIONS', 'eventState': 'INTER...","{'updatedAt': '0', 'netSportCurrentGameState':...",NaN,NaN
5,814872,2024-05-29T09:15:00Z,2024-05-30T20:30:13.307Z,TENNIS,INTERRUPTED,"[{'id': 94, 'name': 'Koolhof W / Mektic N', 'p...",RUNNING,1,"{'id': 14, 'name': 'French Open Men Doubles', ...",[{'id': 'a8ba9e2f-a1a8-3aaa-8497-8c8eaf288718'...,...,"[{'providerId': '81', 'eventId': '537759095111...",NaN,"{'subgroupNameKey': 'French Open Men Doubles, ...",2024-05-30T20:30:13.434Z,"[awayParticipantStateLocation:UNKNOWN, venueSt...","{'total': {'home': {'sets': 0, 'games': 5, 'po...","{'clockType': 'SECTIONS', 'eventState': 'INTER...","{'updatedAt': '0', 'netSportCurrentGameState':...",NaN,NaN
6,817801,2024-05-30T17:30:00Z,2024-05-30T20:30:45.160Z,TENNIS,SUSPENDED,"[{'id': 15813, 'name': 'Dellien Velasco, Murke...",RUNNING,13,"{'id': 4217, 'name': 'ATP Challenger Vicenza',...",[{'id': 'f393e1b9-39c6-3374-ab01-626366f287f3'...,...,"[{'providerId': '71', 'eventId': '11083298'}, ...",NaN,"{'subgroupNameKey': 'ATP Challenger Vicenza, I...",2024-05-30T20:30:45.295Z,"[awayParticipantStateLocation:OTHER, venueStat...","{'total': {'home': {'sets': 1, 'games': 5, 'po...","{'clockType': 'SECTIONS', 'eventState': 'INTER...","{'updatedAt': '1717094555458', 'netSportCurren...",{'event-widget': {'providerId': '71'}},NaN
7,818400,2024-05-30T22:10:00Z,2024-05-30T23:35:00.996Z,TENNIS,ONGOING,"[{'id': 86509, 'name': 'Deming E / Molnar B E'...",RUNNING,27,"{'id': 2632, 'name': 'ITF USA 17A Doubles (W)'...",[{'id': '71eb97e2-8178-386d-b910-95d32b0ee461'...,...,"[{'providerId': '90', 'eventId': '50438195'}, ...",NaN,"{'subgroupNameKey': 'ITF USA 17A, Women Double...",2024-05-30T23:35:01.128Z,"[venueStateLocation:US-CA, awayParticipantStat...","{'total': {'home': {'sets': 0, 'games': 2, 'po...","{'clockType': 'SECTIONS', 'eventState': 'RUNNI...","{'updatedAt': '0', 'netSportCurrentGameState':...",NaN,NaN
8,818390,2024-05-30T22:40:00Z,2024-05-30T23:34:46.780Z,TENNIS,ONGOING,"[{'id': 86510, 'name': 'Gorzny S / Tien L', 'p...",RUNNING,24,"{'id': 2170, 'name': 'ITF USA F11 Doubles (M)'...",[{'id': '2bda429d-945c-31f7-98d4-a3821e16eb0b'...,...,"[{'providerId': '90', 'eventId': '50438143'}, ...",NaN,"{'subgroupNameKey': 'ITF USA F11, Men Doubles,...",2024-05-30T23:34:46.911Z,"[venueStateLocation:US-CA, awayParticipantStat...","{'total': {'home': {'sets': 1, 'games': 2, 'po...","{'clockType': 'SECTIONS', 'eventState': 'RUNNI...","{'updatedAt': '0', 'netSportCurrentGameState':...",NaN,NaN
9,817355,2024-05-30T23:00:00Z,2024-05-30T23:34:52.766Z,BASKETBALL,ONGOING,"[{'id': 13787, 'name': 'Fever', 'position': 'H...",RUNNING,19,"{'id': 77, 'name': 'WNBA', 'parentGroup': {'id...",[{'id': 'df4c4877-9208-387b-91f1-1f8f366e0541'...,...,"[{'providerId': '49', 'eventId': '23148'}, {'p...",NaN,"{'subgroupNameKey': 'WNBA, Western Conference'...",2024-05-30T23:34:52.905Z,"[sgp-pre, homeParticipantStateLocation:US-IN, ...","{'total': {'home': {'value': 25}, 'away': {'va...","{'clockType': 'TIMER', 'eventState': 'IN_PAUSE...",NaN,NaN,NaN
10,817823,2024-05-30T23:00:00Z,2024-05-30T23:35:01.250Z,FOOTBALL,ONGOING,"[{'id': 34816, 'name': 'Venezuela (W)', 'posit...",RUNNING,37,"{'id': 3988, 'name': 'Int. Friendly Games (W)'...",[{'id': '22a3d197-d423-3e12-9042-dc3ed6c9d709'...,...,"[{'providerId': '81', 'eventId': '539568127210...",NaN,{'subgroupNameKey': 'International Friendly Ga...,2024-05-30T23:35:01.381Z,"[blockedCO, sgp-pre, awayParticipantStateLocat...","{'total': {'home': {'value': 0}, 'away': {'val...","{'clockType': 'STOPWATCH', 'eventState': 'RUNN...",NaN,NaN,"{'total': {'home': {'CORNER': 3, 'YELLOW_CARD'..."
11,818124,2024-05-30T23:10:00Z,2024-05-30T23:34:02.313Z,BASEBALL,ONGOING,"[{'id': 60340, 'name': 'Mets', 'position': 'HO...",RUNNING,91,"{'id': 30, 'name': 'MLB', 'parentGroup': {'id'...",[{'id': '0f9bf9d3-8684-37c7-825f-96edeb1bf655'...,...,"[{'providerId': '49', 'eventId': '23124'}, {'p...",NaN,"{'subgroupNameKey': 'MLB, National League West...",2024-05-30T23:34:02.462Z,"[awayParticipantStateLocation:US-AZ, homeParti...","{'total': {'home': {'value': 0}, 'away': {'val...","{'clockType': 'SECTIONS', 'eventState': 'RUNNI...","{'updatedAt': '1717112041913', 'baseballCurren...",NaN,NaN
12,818128,2024-05-30T23:20:00Z,2024-05-30T23:33:09.535Z,BASEBALL,ONGOING,"[{'id': 85772, 'name': 'Braves', 'position': '...",RUNNING,100,"{'id': 30, 'name': 'MLB', 'parentGroup': {'id'...",[{'id': '04e1eeb9-2b6c-3c46-896c-2ada136f40f3'...,...,"[{'providerId': '49', 'eventId': '23126'}, {'p...",NaN,"{'subgroupNameKey': 'MLB, National League East...",2024-05-30T23:33:09.705Z,"[awayParticipantStateLocation:US-DC, homeParti...","{'total': {'home': {'value': 0}, 'away': {'val...","{'clockType': 'SECTIONS', 'eventState': 'RUNNI...","{'updatedAt': '1717111989140', 'baseballCurren...",NaN,NaN
13,818841,2024-05-30T23:30:00Z,2024-05-30T23:34:58.817Z,TABLE_TENNIS,ONGOING,"[{'id': 70152, 'name': 'Zatecka, Ladislav', 'p...",RUNNING,11,"{'id': 7002, 'name': 'Czech Liga Pro', 'parent...",[{'id': 'dbad609d-1c31-35d8-a5ca-d2bd99c375f4'...,...,"[{'providerId': '84', 'eventId': '540444474822...",NaN,"{'subgroupNameKey': 'Czech Liga Pro', 'best_of...",2024-05-30T23:34:58.944Z,"[awayParticipantStateLocation:OTHER, venueStat...","{'total': {'home': {'games': 0}, 'away': {'gam...","{'clockType': 'SECTIONS', 'eventState': 'RUNNI...","{'updatedAt': '0', 'netSportCurrentGameState':...",NaN,NaN
14,818843,2024-05-30T23:30:00Z,2024-05-30T23:34:52.625Z,TABLE_TENNIS,ONGOING,"[{'id': 76612, 'name': 'Sychra, Martin', 'posi...",RUNNING,9,"{'id': 7002, 'name': 'Czech Liga Pro', 'parent...",[{'id': '18da78cf-77e2-3a21-a89d-c90b9f3a0ceb'...,...,"[{'providerId': '84', 'eventId': '540455166953...",NaN,"{'subgroupNameKey': 'Czech Liga Pro', 'best_of...",2024-05-30T23:34:52.758Z,"[awayParticipantStateLocation:OTHER, venueStat...","{'total': {'home': {'games': 1}, 'away': {'gam...","{'clockType': 'SECTIONS', 'eventState': 'RUNNI...","{'updatedAt': '0', 'netSportCurrentGameState':...",NaN,NaN

In [107]:
df.to_csv('data/csv_double_quotes.csv', index=False, quotechar='"', quoting=2)

In [283]:
df["participants"]

0     [{'id': 86605, 'name': 'Hammer, Marc', 'positi...
1     [{'id': 86144, 'name': 'Jacquemot E / Tan H', ...
2     [{'id': 78469, 'name': 'Dolehide CA / Krawczyk...
3     [{'id': 94, 'name': 'Koolhof W / Mektic N', 'p...
4     [{'id': 30935, 'name': 'Du Toit, Jared', 'posi...
5     [{'id': 15813, 'name': 'Dellien Velasco, Murke...
6     [{'id': 86742, 'name': 'Paul, Yannik', 'positi...
7     [{'id': 3598, 'name': 'Langasque, Romain', 'po...
8     [{'id': 848, 'name': 'Danilovic, Olga', 'posit...
9     [{'id': 64, 'name': 'Hokkaido Nippon-Ham Fight...
10    [{'id': 167, 'name': 'Orix Buffaloes', 'positi...
11    [{'id': 16992, 'name': 'Cornet A / Ferro F', '...
12    [{'id': 166, 'name': 'Chiba Lotte Marines', 'p...
13    [{'id': 8478, 'name': 'Birrell, Kimberly', 'po...
14    [{'id': 1050, 'name': 'Saitama Seibu Lions', '...
15    [{'id': 67, 'name': 'Tohoku Rakuten Golden Eag...
16    [{'id': 8188, 'name': 'Oberleitner, Neil', 'po...
17    [{'id': 34668, 'name': 'Heidelberg United FC',...
Name: participants, dtype: object

In [209]:
participants_df = df['participants'].apply(pd.Series)

In [217]:
participants_df

,0,1,2,3,4,5,6,7,8,9,...,147,148,149,150,151,152,153,154,155,156
0,"{'id': 86605, 'name': 'Hammer, Marc', 'positio...","{'id': 86608, 'name': 'Friedrichsen, Sebastian...","{'id': 86742, 'name': 'Paul, Yannik', 'positio...","{'id': 86743, 'name': 'McKibbin, Tom', 'positi...","{'id': 3324, 'name': 'Wiesberger, Bernd', 'pos...","{'id': 86549, 'name': 'Lawrence, Thriston', 'p...","{'id': 86615, 'name': 'Schott, Freddy', 'posit...","{'id': 86554, 'name': 'Forsstrom, Simon', 'pos...","{'id': 86623, 'name': 'Tillmanns, Tim', 'posit...","{'id': 8138, 'name': 'Hill, Callum', 'position...",...,"{'id': 86544, 'name': 'Enoch, Rhys', 'position...","{'id': 86568, 'name': 'Johannessen, Kristian K...","{'id': 86576, 'name': 'Williams, Robin', 'posi...","{'id': 86593, 'name': 'Jordan, Matthew', 'posi...","{'id': 86745, 'name': 'Fitzpatrick, Alex', 'po...","{'id': 86572, 'name': 'Dean, Joe', 'position':...","{'id': 3310, 'name': 'Cabrera Bello, Rafael', ...","{'id': 7596, 'name': 'Molinari, Edoardo', 'pos...","{'id': 86548, 'name': 'Rusch, Benjamin', 'posi...","{'id': 86567, 'name': 'Prinsloo, Jaco', 'posit..."
1,"{'id': 71233, 'name': 'Kato M / Kichenok N', '...","{'id': 39274, 'name': 'Saville D / Tomljanovic...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"{'id': 86144, 'name': 'Jacquemot E / Tan H', '...","{'id': 30924, 'name': 'Mihalikova T / Noskova ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"{'id': 38216, 'name': 'Johnson L / Mansouri S'...","{'id': 27433, 'name': 'Arneodo R / Weissborn T...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"{'id': 78469, 'name': 'Dolehide CA / Krawczyk ...","{'id': 86146, 'name': 'Gracheva V / Lechemia E...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,"{'id': 94, 'name': 'Koolhof W / Mektic N', 'po...","{'id': 16499, 'name': 'Arends S / Middelkoop M...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,"{'id': 15813, 'name': 'Dellien Velasco, Murkel...","{'id': 468, 'name': 'Travaglia, Stefano', 'pos...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,"{'id': 79831, 'name': 'Luciano, Lavinia', 'pos...","{'id': 20489, 'name': 'Tanasie, Lavinia', 'pos...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,"{'id': 6281, 'name': 'Zvonaru, Ioana', 'positi...","{'id': 16128, 'name': 'Ferrara, Virginia', 'po...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,"{'id': 8231, 'name': 'Ovcharenko, Ekaterina', ...","{'id': 63159, 'name': 'Goina, Patricia Georgia...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,"{'id': 44858, 'name': 'Hrazdil, Jan', 'positio...","{'id': 23089, 'name': 'Schiessl, Joao Eduardo'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,"{'id': 5596, 'name': 'Prisacariu, Andreea', 'p...","{'id': 15335, 'name': 'Hageman, Madelief', 'po...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,"{'id': 7146, 'name': 'Snitari, Ilya', 'positio...","{'id': 14741, 'name': 'Marinescu, Mihai Razvan...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,"{'id': 8578, 'name': 'Sorrentino, Luigi', 'pos...","{'id': 10082, 'name': 'Wehnelt, Kai', 'positio...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,"{'id': 86467, 'name': 'Abe H / Morisaki K', 'p...","{'id': 58913, 'name': 'Inoue A / Ozeki M', 'po...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,"{'id': 36252, 'name': 'Taranaki Mountainairs',...","{'id': 36204, 'name': 'Otago Nuggets', 'positi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,"{'id': 2377, 'name': 'Bielinskyi, Viacheslav',...","{'id': 5967, 'name': 'Mashtakov, Nikita', 'pos...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,"{'id': 19005, 'name': 'Polcanova, Sofia', 'pos...","{'id': 26803, 'name': 'Wang, Yidi', 'position'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [214]:
participants_df.columns.stop

157

In [218]:
for i in range(participants_df.columns.stop):
    temp_df = participants_df[i].apply(pd.Series)
    print(temp_df.head())

      id                      name position abbreviation
0  86605              Hammer, Marc    OTHER          HAM
1  71233       Kato M / Kichenok N     HOME          KKI
2  86144       Jacquemot E / Tan H     HOME          JTA
3  38216    Johnson L / Mansouri S     HOME          JMA
4  78469  Dolehide CA / Krawczyk D     HOME          DKR
      id                       name position abbreviation
0  86608    Friedrichsen, Sebastian    OTHER          FRI
1  39274  Saville D / Tomljanovic A     AWAY          STO
2  30924   Mihalikova T / Noskova L     AWAY          MNO
3  27433  Arneodo R / Weissborn T-S     AWAY          AWE
4  86146    Gracheva V / Lechemia E     AWAY          GLE
        id          name position abbreviation   0
0  86742.0  Paul, Yannik    OTHER          PAU NaN
1      NaN           NaN      NaN          NaN NaN
2      NaN           NaN      NaN          NaN NaN
3      NaN           NaN      NaN          NaN NaN
4      NaN           NaN      NaN          NaN NaN
        id           name position abbreviation   0
0  86743.0  McKibbin, Tom    OTHER          MCK NaN
1      NaN            NaN      NaN          NaN NaN
2      NaN            NaN      NaN          NaN NaN
3      NaN            NaN      NaN          NaN NaN
4      NaN            NaN      NaN          NaN NaN
       id               name position abbreviation   0
0  3324.0  Wiesberger, Bernd    OTHER          WIE NaN
1     NaN                NaN      NaN          NaN NaN
2     NaN                NaN      NaN          NaN NaN
3     NaN                NaN      NaN          NaN NaN
4     NaN                NaN      NaN          NaN NaN
        id                name position abbreviation   0
0  86549.0  Lawrence, Thriston    OTHER          LAW NaN
1      NaN                 NaN      NaN          NaN NaN
2      NaN                 NaN      NaN          NaN NaN
3      NaN                 NaN      NaN          NaN NaN
4      NaN                 NaN      NaN          NaN NaN
        id            name position abbreviation   0
0  86615.0  Schott, Freddy    OTHER          SCH NaN
1      NaN             NaN      NaN          NaN NaN
2      NaN             NaN      NaN          NaN NaN
3      NaN             NaN      NaN          NaN NaN
4      NaN             NaN      NaN          NaN NaN
        id              name position abbreviation   0
0  86554.0  Forsstrom, Simon    OTHER          FOR NaN
1      NaN               NaN      NaN          NaN NaN
2      NaN               NaN      NaN          NaN NaN
3      NaN               NaN      NaN          NaN NaN
4      NaN               NaN      NaN          NaN NaN
        id            name position abbreviation   0
0  86623.0  Tillmanns, Tim    OTHER          TIL NaN
1      NaN             NaN      NaN          NaN NaN
2      NaN             NaN      NaN          NaN NaN
3      NaN             NaN      NaN          NaN NaN
4      NaN             NaN      NaN          NaN NaN
       id          name position abbreviation   0
0  8138.0  Hill, Callum    OTHER          HIL NaN
1     NaN           NaN      NaN          NaN NaN
2     NaN           NaN      NaN          NaN NaN
3     NaN           NaN      NaN          NaN NaN
4     NaN           NaN      NaN          NaN NaN
       id                   name position abbreviation   0
0  3418.0  Lorenzo-Vera, Michael    OTHER          LOR NaN
1     NaN                    NaN      NaN          NaN NaN
2     NaN                    NaN      NaN          NaN NaN
3     NaN                    NaN      NaN          NaN NaN
4     NaN                    NaN      NaN          NaN NaN
       id             name position abbreviation   0
0  8023.0  Hillier, Daniel    OTHER          HIL NaN
1     NaN              NaN      NaN          NaN NaN
2     NaN              NaN      NaN          NaN NaN
3     NaN              NaN      NaN          NaN NaN
4     NaN              NaN      NaN          NaN NaN
        id          name position abbreviation   0
0  86531.0  Siem, Marcel    OTHER          SIE NaN
1      NaN           NaN      NaN          NaN NaN
2      NaN           NaN      NaN          NaN NaN
3      NaN           NaN      NaN          NaN NaN
4      NaN           NaN      NaN          NaN NaN
        id           name position abbreviation   0
0  86558.0  Brown, Daniel    OTHER          BRO NaN
1      NaN            NaN      NaN          NaN NaN
2      NaN            NaN      NaN          NaN NaN
3      NaN            NaN      NaN          NaN NaN
4      NaN            NaN      NaN          NaN NaN
        id             name position abbreviation   0
0  86595.0  Nakajima, Keita    OTHER          NAK NaN
1      NaN              NaN      NaN          NaN NaN
2      NaN              NaN      NaN          NaN NaN
3      NaN              NaN      NaN          NaN NaN
4      NaN              NaN      NaN          NaN NaN
        id           name position abbreviation   0
0  86599.0  Barron, Haydn    OTHER          BAR NaN
1      NaN            NaN      NaN          NaN NaN
2      NaN            NaN      NaN          NaN NaN
3      NaN            NaN      NaN          NaN NaN
4      NaN            NaN      NaN          NaN NaN
        id        name position abbreviation   0
0  86612.0  Jones, Sam    OTHER          JON NaN
1      NaN         NaN      NaN          NaN NaN
2      NaN         NaN      NaN          NaN NaN
3      NaN         NaN      NaN          NaN NaN
4      NaN         NaN      NaN          NaN NaN
        id                 name position abbreviation   0
0  86603.0  Helligkilde, Marcus    OTHER          HEL NaN
1      NaN                  NaN      NaN          NaN NaN
2      NaN                  NaN      NaN          NaN NaN
3      NaN                  NaN      NaN          NaN NaN
4      NaN                  NaN      NaN          NaN NaN
       id       name position abbreviation   0
0  7604.0  Wu, Ashun    OTHER          ASH NaN
1     NaN        NaN      NaN          NaN NaN
2     NaN        NaN      NaN          NaN NaN
3     NaN        NaN      NaN          NaN NaN
4     NaN        NaN      NaN          NaN NaN
        id               name position abbreviation   0
0  86564.0  Veerman, Johannes    OTHER          VEE NaN
1      NaN                NaN      NaN          NaN NaN
2      NaN                NaN      NaN          NaN NaN
3      NaN                NaN      NaN          NaN NaN
4      NaN                NaN      NaN          NaN NaN
        id               name position abbreviation   0
0  86566.0  Van Driel, Darius    OTHER          VAN NaN
1      NaN                NaN      NaN          NaN NaN
2      NaN                NaN      NaN          NaN NaN
3      NaN                NaN      NaN          NaN NaN
4      NaN                NaN      NaN          NaN NaN
        id             name position abbreviation   0
0  86596.0  Enefer, William    OTHER          ENE NaN
1      NaN              NaN      NaN          NaN NaN
2      NaN              NaN      NaN          NaN NaN
3      NaN              NaN      NaN          NaN NaN
4      NaN              NaN      NaN          NaN NaN
       id                 name position abbreviation   0
0  8101.0  Kieffer, Maximilian    OTHER          KIE NaN
1     NaN                  NaN      NaN          NaN NaN
2     NaN                  NaN      NaN          NaN NaN
3     NaN                  NaN      NaN          NaN NaN
4     NaN                  NaN      NaN          NaN NaN
        id              name position abbreviation   0
0  86550.0  Gouveia, Ricardo    OTHER          GOU NaN
1      NaN               NaN      NaN          NaN NaN
2      NaN               NaN      NaN          NaN NaN
3      NaN               NaN      NaN          NaN NaN
4      NaN               NaN      NaN          NaN NaN
       id             name position abbreviation   0
0  8103.0  Jamieson, Scott    OTHER          JAM NaN
1     NaN              NaN      NaN          NaN NaN
2     NaN              NaN      NaN          NaN NaN
3     NaN              NaN      NaN          NaN NaN
4     NaN              NaN      NaN          NaN NaN
        id                name position abbreviation   0
0  86581.0  Del Rey, Alejandro    OTHER          DEL NaN
1      NaN                 NaN      NaN          NaN NaN
2      NaN                 NaN      NaN          NaN NaN
3      NaN                 NaN      NaN          NaN NaN
4      NaN                 NaN      NaN          NaN NaN
        id           name position abbreviation   0
0  86626.0  Weber, Jordan    OTHER          WEB NaN
1      NaN            NaN      NaN          NaN NaN
2      NaN            NaN      NaN          NaN NaN
3      NaN            NaN      NaN          NaN NaN
4      NaN            NaN      NaN          NaN NaN
       id        name position abbreviation   0
0  7609.0  Law, David    OTHER          LAW NaN
1     NaN         NaN      NaN          NaN NaN
2     NaN         NaN      NaN          NaN NaN
3     NaN         NaN      NaN          NaN NaN
4     NaN         NaN      NaN          NaN NaN
       id             name position abbreviation   0
0  8112.0  Otaegui, Adrian    OTHER          OTA NaN
1     NaN              NaN      NaN          NaN NaN
2     NaN              NaN      NaN          NaN NaN
3     NaN              NaN      NaN          NaN NaN
4     NaN              NaN      NaN          NaN NaN
        id              name position abbreviation   0
0  86532.0  Fichardt, Darren    OTHER          FIC NaN
1      NaN               NaN      NaN          NaN NaN
2      NaN               NaN      NaN          NaN NaN
3      NaN               NaN      NaN          NaN NaN
4      NaN               NaN      NaN          NaN NaN
        id           name position abbreviation   0
0  86611.0  Jarvis, Casey    OTHER          JAR NaN
1      NaN            NaN      NaN          NaN NaN
2      NaN            NaN      NaN          NaN NaN
3      NaN            NaN      NaN          NaN NaN
4      NaN            NaN      NaN          NaN NaN
        id          name position abbreviation   0
0  86573.0  Hanna, Chase    OTHER          HAN NaN
1      NaN           NaN      NaN          NaN NaN
2      NaN           NaN      NaN          NaN NaN
3      NaN           NaN      NaN          NaN NaN
4      NaN           NaN      NaN          NaN NaN
       id            name position abbreviation   0
0  8091.0  Wilson, Oliver    OTHER          WIL NaN
1     NaN             NaN      NaN          NaN NaN
2     NaN             NaN      NaN          NaN NaN
3     NaN             NaN      NaN          NaN NaN
4     NaN             NaN      NaN          NaN NaN
        id           name position abbreviation   0
0  86571.0  Ruuska, Lauri    OTHER          RUU NaN
1      NaN            NaN      NaN          NaN NaN
2      NaN            NaN      NaN          NaN NaN
3      NaN            NaN      NaN          NaN NaN
4      NaN            NaN      NaN          NaN NaN
        id          name position abbreviation   0
0  86746.0  Bachem, Nick    OTHER          BAC NaN
1      NaN           NaN      NaN          NaN NaN
2      NaN           NaN      NaN          NaN NaN
3      NaN           NaN      NaN          NaN NaN
4      NaN           NaN      NaN          NaN NaN
        id             name position abbreviation   0
0  86559.0  Sordet, Clement    OTHER          SOR NaN
1      NaN              NaN      NaN          NaN NaN
2      NaN              NaN      NaN          NaN NaN
3      NaN              NaN      NaN          NaN NaN
4      NaN              NaN      NaN          NaN NaN
       id          name position abbreviation   0
0  8260.0  Syme, Connor    OTHER          SYM NaN
1     NaN           NaN      NaN          NaN NaN
2     NaN           NaN      NaN          NaN NaN
3     NaN           NaN      NaN          NaN NaN
4     NaN           NaN      NaN          NaN NaN

       id                name position abbreviation   0
0  3597.0  Southgate, Matthew    OTHER          SOU NaN
1     NaN                 NaN      NaN          NaN NaN
2     NaN                 NaN      NaN          NaN NaN
3     NaN                 NaN      NaN          NaN NaN
4     NaN                 NaN      NaN          NaN NaN
       id          name position abbreviation   0
0  8140.0  Arnaus, Adri    OTHER          ARN NaN
1     NaN           NaN      NaN          NaN NaN
2     NaN           NaN      NaN          NaN NaN
3     NaN           NaN      NaN          NaN NaN
4     NaN           NaN      NaN          NaN NaN
        id                     name position abbreviation   0
0  86553.0  Cantero Gutierrez, Ivan    OTHER          CAN NaN
1      NaN                      NaN      NaN          NaN NaN
2      NaN                      NaN      NaN          NaN NaN
3      NaN                      NaN      NaN          NaN NaN
4      NaN                      NaN      NaN          NaN NaN
       id              name position abbreviation   0
0  3596.0  Pepperell, Eddie    OTHER          PEP NaN
1     NaN               NaN      NaN          NaN NaN
2     NaN               NaN      NaN          NaN NaN
3     NaN               NaN      NaN          NaN NaN
4     NaN               NaN      NaN          NaN NaN
       id              name position abbreviation   0
0  3374.0  Hojgaard, Rasmus    OTHER          HOJ NaN
1     NaN               NaN      NaN          NaN NaN
2     NaN               NaN      NaN          NaN NaN
3     NaN               NaN      NaN          NaN NaN
4     NaN               NaN      NaN          NaN NaN
        id            name position abbreviation   0
0  86600.0  Elvira, Manuel    OTHER          ELV NaN
1      NaN             NaN      NaN          NaN NaN
2      NaN             NaN      NaN          NaN NaN
3      NaN             NaN      NaN          NaN NaN
4      NaN             NaN      NaN          NaN NaN
        id               name position abbreviation   0
0  86546.0  Porteous, Garrick    OTHER          POR NaN
1      NaN                NaN      NaN          NaN NaN
2      NaN                NaN      NaN          NaN NaN
3      NaN                NaN      NaN          NaN NaN
4      NaN                NaN      NaN          NaN NaN
        id            name position abbreviation   0
0  86555.0  Girrbach, Joel    OTHER          GIR NaN
1      NaN             NaN      NaN          NaN NaN
2      NaN             NaN      NaN          NaN NaN
3      NaN             NaN      NaN          NaN NaN
4      NaN             NaN      NaN          NaN NaN
        id           name position abbreviation   0
0  86618.0  Bairstow, Sam    OTHER          BAI NaN
1      NaN            NaN      NaN          NaN NaN
2      NaN            NaN      NaN          NaN NaN
3      NaN            NaN      NaN          NaN NaN
4      NaN            NaN      NaN          NaN NaN
       id           name position abbreviation   0
0  8124.0  Winther, Jeff    OTHER          WIN NaN
1     NaN            NaN      NaN          NaN NaN
2     NaN            NaN      NaN          NaN NaN
3     NaN            NaN      NaN          NaN NaN
4     NaN            NaN      NaN          NaN NaN
        id            name position abbreviation   0
0  86543.0  Kofstad, Espen    OTHER          KOF NaN
1      NaN             NaN      NaN          NaN NaN
2      NaN             NaN      NaN          NaN NaN
3      NaN             NaN      NaN          NaN NaN
4      NaN             NaN      NaN          NaN NaN
        id           name position abbreviation   0
0  86536.0  Nemecz, Lukas    OTHER          NEM NaN
1      NaN            NaN      NaN          NaN NaN
2      NaN            NaN      NaN          NaN NaN
3      NaN            NaN      NaN          NaN NaN
4      NaN            NaN      NaN          NaN NaN
        id               name position abbreviation   0
0  86748.0  Katsuragawa, Yuto    OTHER          KAT NaN
1      NaN                NaN      NaN          NaN NaN
2      NaN                NaN      NaN          NaN NaN
3      NaN                NaN      NaN          NaN NaN
4      NaN                NaN      NaN          NaN NaN
        id            name position abbreviation   0
0  86602.0  Ko, Jeong Weon    OTHER          JEO NaN
1      NaN             NaN      NaN          NaN NaN
2      NaN             NaN      NaN          NaN NaN
3      NaN             NaN      NaN          NaN NaN
4      NaN             NaN      NaN          NaN NaN
       id             name position abbreviation   0
0  8137.0  Rozner, Antoine    OTHER          ROZ NaN
1     NaN              NaN      NaN          NaN NaN
2     NaN              NaN      NaN          NaN NaN
3     NaN              NaN      NaN          NaN NaN
4     NaN              NaN      NaN          NaN NaN
        id                        name position abbreviation   0
0  86613.0  Neergaard-Petersen, Rasmus    OTHER          NEE NaN
1      NaN                         NaN      NaN          NaN NaN
2      NaN                         NaN      NaN          NaN NaN
3      NaN                         NaN      NaN          NaN NaN
4      NaN                         NaN      NaN          NaN NaN
        id              name position abbreviation   0
0  86597.0  Mansell, Richard    OTHER          MAN NaN
1      NaN               NaN      NaN          NaN NaN
2      NaN               NaN      NaN          NaN NaN
3      NaN               NaN      NaN          NaN NaN
4      NaN               NaN      NaN          NaN NaN
        id              name position abbreviation   0
0  86580.0  Rugumayo, Ronald    OTHER          RUG NaN
1      NaN               NaN      NaN          NaN NaN
2      NaN               NaN      NaN          NaN NaN
3      NaN               NaN      NaN          NaN NaN
4      NaN               NaN      NaN          NaN NaN
       id                name position abbreviation   0
0  8129.0  Sharma, Shubhankar    OTHER          SHA NaN
1     NaN                 NaN      NaN          NaN NaN
2     NaN                 NaN      NaN          NaN NaN
3     NaN                 NaN      NaN          NaN NaN
4     NaN                 NaN      NaN          NaN NaN
       id                name position abbreviation   0
0  8080.0  Colsaerts, Nicolas    OTHER          COL NaN
1     NaN                 NaN      NaN          NaN NaN
2     NaN                 NaN      NaN          NaN NaN
3     NaN                 NaN      NaN          NaN NaN
4     NaN                 NaN      NaN          NaN NaN
        id                      name position abbreviation   0
0  75131.0  Goth-Rasmussen, Jonathan    OTHER          GOT NaN
1      NaN                       NaN      NaN          NaN NaN
2      NaN                       NaN      NaN          NaN NaN
3      NaN                       NaN      NaN          NaN NaN
4      NaN                       NaN      NaN          NaN NaN
       id           name position abbreviation   0
0  3584.0  Pavan, Andrea    OTHER          PAV NaN
1     NaN            NaN      NaN          NaN NaN
2     NaN            NaN      NaN          NaN NaN
3     NaN            NaN      NaN          NaN NaN
4     NaN            NaN      NaN          NaN NaN
        id            name position abbreviation   0
0  86533.0  Manley, Stuart    OTHER          MAN NaN
1      NaN             NaN      NaN          NaN NaN
2      NaN             NaN      NaN          NaN NaN
3      NaN             NaN      NaN          NaN NaN
4      NaN             NaN      NaN          NaN NaN
       id            name position abbreviation   0
0  3349.0  Sullivan, Andy    OTHER          SUL NaN
1     NaN             NaN      NaN          NaN NaN
2     NaN             NaN      NaN          NaN NaN
3     NaN             NaN      NaN          NaN NaN
4     NaN             NaN      NaN          NaN NaN
       id             name position abbreviation   0
0  7595.0  Kjeldsen, Soren    OTHER          KJE NaN
1     NaN              NaN      NaN          NaN NaN
2     NaN              NaN      NaN          NaN NaN
3     NaN              NaN      NaN          NaN NaN
4     NaN              NaN      NaN          NaN NaN

       id              name position abbreviation   0
0  3346.0  Schwab, Matthias    OTHER          SCH NaN
1     NaN               NaN      NaN          NaN NaN
2     NaN               NaN      NaN          NaN NaN
3     NaN               NaN      NaN          NaN NaN
4     NaN               NaN      NaN          NaN NaN
       id              name position abbreviation   0
0  7599.0  Guerrier, Julien    OTHER          GUE NaN
1     NaN               NaN      NaN          NaN NaN
2     NaN               NaN      NaN          NaN NaN
3     NaN               NaN      NaN          NaN NaN
4     NaN               NaN      NaN          NaN NaN
       id              name position abbreviation   0
0  3419.0  Frittelli, Dylan    OTHER          FRI NaN
1     NaN               NaN      NaN          NaN NaN
2     NaN               NaN      NaN          NaN NaN
3     NaN               NaN      NaN          NaN NaN
4     NaN               NaN      NaN          NaN NaN
       id              name position abbreviation   0
0  3600.0  Armitage, Marcus    OTHER          ARM NaN
1     NaN               NaN      NaN          NaN NaN
2     NaN               NaN      NaN          NaN NaN
3     NaN               NaN      NaN          NaN NaN
4     NaN               NaN      NaN          NaN NaN
        id               name position abbreviation   0
0  86535.0  Figueiredo, Pedro    OTHER          FIG NaN
1      NaN                NaN      NaN          NaN NaN
2      NaN                NaN      NaN          NaN NaN
3      NaN                NaN      NaN          NaN NaN
4      NaN                NaN      NaN          NaN NaN
        id               name position abbreviation   0
0  86587.0  Lacroix, Frederic    OTHER          LAC NaN
1      NaN                NaN      NaN          NaN NaN
2      NaN                NaN      NaN          NaN NaN
3      NaN                NaN      NaN          NaN NaN
4      NaN                NaN      NaN          NaN NaN
        id                         name position abbreviation   0
0  86557.0  Garcia Rodriguez, Sebastian    OTHER          GAR NaN
1      NaN                          NaN      NaN          NaN NaN
2      NaN                          NaN      NaN          NaN NaN
3      NaN                          NaN      NaN          NaN NaN
4      NaN                          NaN      NaN          NaN NaN
        id                name position abbreviation   0
0  86562.0  Kruyswijk, Jacques    OTHER          KRU NaN
1      NaN                 NaN      NaN          NaN NaN
2      NaN                 NaN      NaN          NaN NaN
3      NaN                 NaN      NaN          NaN NaN
4      NaN                 NaN      NaN          NaN NaN
        id             name position abbreviation   0
0  86604.0  Besard, Matthis    OTHER          BES NaN
1      NaN              NaN      NaN          NaN NaN
2      NaN              NaN      NaN          NaN NaN
3      NaN              NaN      NaN          NaN NaN
4      NaN              NaN      NaN          NaN NaN
       id                name position abbreviation   0
0  8106.0  Kawamura, Masahiro    OTHER          KAW NaN
1     NaN                 NaN      NaN          NaN NaN
2     NaN                 NaN      NaN          NaN NaN
3     NaN                 NaN      NaN          NaN NaN
4     NaN                 NaN      NaN          NaN NaN
       id               name position abbreviation   0
0  8098.0  Larrazabal, Pablo    OTHER          LAR NaN
1     NaN                NaN      NaN          NaN NaN
2     NaN                NaN      NaN          NaN NaN
3     NaN                NaN      NaN          NaN NaN
4     NaN                NaN      NaN          NaN NaN
        id            name position abbreviation   0
0  86575.0  Davidson, Jack    OTHER          DAV NaN
1      NaN             NaN      NaN          NaN NaN
2      NaN             NaN      NaN          NaN NaN
3      NaN             NaN      NaN          NaN NaN
4      NaN             NaN      NaN          NaN NaN
        id            name position abbreviation   0
0  86609.0  Ravetto, David    OTHER          RAV NaN
1      NaN             NaN      NaN          NaN NaN
2      NaN             NaN      NaN          NaN NaN
3      NaN             NaN      NaN          NaN NaN
4      NaN             NaN      NaN          NaN NaN
        id             name position abbreviation   0
0  86584.0  Moolman, Pieter    OTHER          MOO NaN
1      NaN              NaN      NaN          NaN NaN
2      NaN              NaN      NaN          NaN NaN
3      NaN              NaN      NaN          NaN NaN
4      NaN              NaN      NaN          NaN NaN
        id           name position abbreviation   0
0  86620.0  Vaillant, Tom    OTHER          VAI NaN
1      NaN            NaN      NaN          NaN NaN
2      NaN            NaN      NaN          NaN NaN
3      NaN            NaN      NaN          NaN NaN
4      NaN            NaN      NaN          NaN NaN
        id                 name position abbreviation   0
0  86551.0  Chouhan, Om Prakash    OTHER          CHO NaN
1      NaN                  NaN      NaN          NaN NaN
2      NaN                  NaN      NaN          NaN NaN
3      NaN                  NaN      NaN          NaN NaN
4      NaN                  NaN      NaN          NaN NaN
       id         name position abbreviation   0
0  8033.0  Chen, Guxin    OTHER          CHE NaN
1     NaN          NaN      NaN          NaN NaN
2     NaN          NaN      NaN          NaN NaN
3     NaN          NaN      NaN          NaN NaN
4     NaN          NaN      NaN          NaN NaN
        id             name position abbreviation   0
0  86610.0  Nicholas, James    OTHER          NIC NaN
1      NaN              NaN      NaN          NaN NaN
2      NaN              NaN      NaN          NaN NaN
3      NaN              NaN      NaN          NaN NaN
4      NaN              NaN      NaN          NaN NaN
        id                     name position abbreviation   0
0  86534.0  Garcia-Heredia, Alfredo    OTHER          GAR NaN
1      NaN                      NaN      NaN          NaN NaN
2      NaN                      NaN      NaN          NaN NaN
3      NaN                      NaN      NaN          NaN NaN
4      NaN                      NaN      NaN          NaN NaN
       id               name position abbreviation   0
0  3598.0  Langasque, Romain    OTHER          LAN NaN
1     NaN                NaN      NaN          NaN NaN
2     NaN                NaN      NaN          NaN NaN
3     NaN                NaN      NaN          NaN NaN
4     NaN                NaN      NaN          NaN NaN
        id               name position abbreviation   0
0  86552.0  Schneider, Marcel    OTHER          SCH NaN
1      NaN                NaN      NaN          NaN NaN
2      NaN                NaN      NaN          NaN NaN
3      NaN                NaN      NaN          NaN NaN
4      NaN                NaN      NaN          NaN NaN
        id            name position abbreviation   0
0  86592.0  Wilson, Andrew    OTHER          WIL NaN
1      NaN             NaN      NaN          NaN NaN
2      NaN             NaN      NaN          NaN NaN
3      NaN             NaN      NaN          NaN NaN
4      NaN             NaN      NaN          NaN NaN
        id              name position abbreviation   0
0  86590.0  Svensson, Jesper    OTHER          SVE NaN
1      NaN               NaN      NaN          NaN NaN
2      NaN               NaN      NaN          NaN NaN
3      NaN               NaN      NaN          NaN NaN
4      NaN               NaN      NaN          NaN NaN
        id          name position abbreviation   0
0  86589.0  Blomme, Adam    OTHER          BLO NaN
1      NaN           NaN      NaN          NaN NaN
2      NaN           NaN      NaN          NaN NaN
3      NaN           NaN      NaN          NaN NaN
4      NaN           NaN      NaN          NaN NaN
       id             name position abbreviation   0
0  3333.0  Willett, Daniel    OTHER          WIL NaN
1     NaN              NaN      NaN          NaN NaN
2     NaN              NaN      NaN          NaN NaN
3     NaN              NaN      NaN          NaN NaN
4     NaN              NaN      NaN          NaN NaN
        id              name position abbreviation   0
0  86542.0  Baldwin, Matthew    OTHER          BAL NaN
1      NaN               NaN      NaN          NaN NaN
2      NaN               NaN      NaN          NaN NaN
3      NaN               NaN      NaN          NaN NaN
4      NaN               NaN      NaN          NaN NaN
       id           name position abbreviation   0
0  8134.0  Smith, Jordan    OTHER          SMI NaN
1     NaN            NaN      NaN          NaN NaN
2     NaN            NaN      NaN          NaN NaN
3     NaN            NaN      NaN          NaN NaN
4     NaN            NaN      NaN          NaN NaN
       id               name position abbreviation   0
0  8008.0  Micheluzzi, David    OTHER          MIC NaN
1     NaN                NaN      NaN          NaN NaN
2     NaN                NaN      NaN          NaN NaN
3     NaN                NaN      NaN          NaN NaN
4     NaN                NaN      NaN          NaN NaN
       id              name position abbreviation   0
0  3594.0  Johnston, Andrew    OTHER          JOH NaN
1     NaN               NaN      NaN          NaN NaN
2     NaN               NaN      NaN          NaN NaN
3     NaN               NaN      NaN          NaN NaN
4     NaN               NaN      NaN          NaN NaN
        id                 name position abbreviation   0
0  86625.0  Broholt Lind, Soren    OTHER          BRO NaN
1      NaN                  NaN      NaN          NaN NaN
2      NaN                  NaN      NaN          NaN NaN
3      NaN                  NaN      NaN          NaN NaN
4      NaN                  NaN      NaN          NaN NaN
        id            name position abbreviation   0
0  86619.0  Kennedy, Frank    OTHER          KEN NaN
1      NaN             NaN      NaN          NaN NaN
2      NaN             NaN      NaN          NaN NaN
3      NaN             NaN      NaN          NaN NaN
4      NaN             NaN      NaN          NaN NaN
       id           name position abbreviation   0
0  8131.0  Crocker, Sean    OTHER          CRO NaN
1     NaN            NaN      NaN          NaN NaN
2     NaN            NaN      NaN          NaN NaN
3     NaN            NaN      NaN          NaN NaN
4     NaN            NaN      NaN          NaN NaN
        id           name position abbreviation   0
0  86578.0  Ahlawat, Veer    OTHER          AHL NaN
1      NaN            NaN      NaN          NaN NaN
2      NaN            NaN      NaN          NaN NaN
3      NaN            NaN      NaN          NaN NaN
4      NaN            NaN      NaN          NaN NaN
        id                         name position abbreviation   0
0  86569.0  Von Dellingshausen, Nicolai    OTHER          VON NaN
1      NaN                          NaN      NaN          NaN NaN
2      NaN                          NaN      NaN          NaN NaN
3      NaN                          NaN      NaN          NaN NaN
4      NaN                          NaN      NaN          NaN NaN
        id            name position abbreviation   0
0  86747.0  Ferguson, Ewen    OTHER          FER NaN
1      NaN             NaN      NaN          NaN NaN
2      NaN             NaN      NaN          NaN NaN
3      NaN             NaN      NaN          NaN NaN
4      NaN             NaN      NaN          NaN NaN
        id           name position abbreviation   0
0  86622.0  Albers, Anton    OTHER          ALB NaN
1      NaN            NaN      NaN          NaN NaN
2      NaN            NaN      NaN          NaN NaN
3      NaN            NaN      NaN          NaN NaN
4      NaN            NaN      NaN          NaN NaN
       id              name position abbreviation   0
0  8133.0  Shinkwin, Callum    OTHER          SHI NaN
1     NaN               NaN      NaN          NaN NaN
2     NaN               NaN      NaN          NaN NaN
3     NaN               NaN      NaN          NaN NaN
4     NaN               NaN      NaN          NaN NaN
        id            name position abbreviation   0
0  86540.0  Strydom, Ockie    OTHER          STR NaN
1      NaN             NaN      NaN          NaN NaN
2      NaN             NaN      NaN          NaN NaN
3      NaN             NaN      NaN          NaN NaN
4      NaN             NaN      NaN          NaN NaN
        id              name position abbreviation   0
0  86583.0  Tarrio, Santiago    OTHER          TAR NaN
1      NaN               NaN      NaN          NaN NaN
2      NaN               NaN      NaN          NaN NaN
3      NaN               NaN      NaN          NaN NaN
4      NaN               NaN      NaN          NaN NaN

       id              name position abbreviation   0
0  8102.0  Scrivener, Jason    OTHER          SCR NaN
1     NaN               NaN      NaN          NaN NaN
2     NaN               NaN      NaN          NaN NaN
3     NaN               NaN      NaN          NaN NaN
4     NaN               NaN      NaN          NaN NaN
       id                    name position abbreviation   0
0  3588.0  Aphinbarnrat, Kiradech    OTHER          APH NaN
1     NaN                     NaN      NaN          NaN NaN
2     NaN                     NaN      NaN          NaN NaN
3     NaN                     NaN      NaN          NaN NaN
4     NaN                     NaN      NaN          NaN NaN
        id           name position abbreviation   0
0  86539.0  Dantorp, Jens    OTHER          DAN NaN
1      NaN            NaN      NaN          NaN NaN
2      NaN            NaN      NaN          NaN NaN
3      NaN            NaN      NaN          NaN NaN
4      NaN            NaN      NaN          NaN NaN
        id           name position abbreviation   0
0  86579.0  Coussaud, Ugo    OTHER          COU NaN
1      NaN            NaN      NaN          NaN NaN
2      NaN            NaN      NaN          NaN NaN
3      NaN            NaN      NaN          NaN NaN
4      NaN            NaN      NaN          NaN NaN
        id                  name position abbreviation   0
0  86561.0  Rottluff, Maximilian    OTHER          ROT NaN
1      NaN                   NaN      NaN          NaN NaN
2      NaN                   NaN      NaN          NaN NaN
3      NaN                   NaN      NaN          NaN NaN
4      NaN                   NaN      NaN          NaN NaN
       id              name position abbreviation   0
0  3605.0  Galletti, Nicolo    OTHER          GAL NaN
1     NaN               NaN      NaN          NaN NaN
2     NaN               NaN      NaN          NaN NaN
3     NaN               NaN      NaN          NaN NaN
4     NaN               NaN      NaN          NaN NaN
        id              name position abbreviation   0
0  86560.0  Scalise, Lorenzo    OTHER          SCA NaN
1      NaN               NaN      NaN          NaN NaN
2      NaN               NaN      NaN          NaN NaN
3      NaN               NaN      NaN          NaN NaN
4      NaN               NaN      NaN          NaN NaN
       id            name position abbreviation   0
0  8120.0  Stone, Brandon    OTHER          STO NaN
1     NaN             NaN      NaN          NaN NaN
2     NaN             NaN      NaN          NaN NaN
3     NaN             NaN      NaN          NaN NaN
4     NaN             NaN      NaN          NaN NaN
       id              name position abbreviation   0
0  8126.0  Paratore, Renato    OTHER          PAR NaN
1     NaN               NaN      NaN          NaN NaN
2     NaN               NaN      NaN          NaN NaN
3     NaN               NaN      NaN          NaN NaN
4     NaN               NaN      NaN          NaN NaN
       id            name position abbreviation   0
0  7610.0  Forrest, Grant    OTHER          FOR NaN
1     NaN             NaN      NaN          NaN NaN
2     NaN             NaN      NaN          NaN NaN
3     NaN             NaN      NaN          NaN NaN
4     NaN             NaN      NaN          NaN NaN
        id          name position abbreviation   0
0  86541.0  Blixt, Jonas    OTHER          BLI NaN
1      NaN           NaN      NaN          NaN NaN
2      NaN           NaN      NaN          NaN NaN
3      NaN           NaN      NaN          NaN NaN
4      NaN           NaN      NaN          NaN NaN
        id         name position abbreviation   0
0  86744.0  Long, Hurly    OTHER          LON NaN
1      NaN          NaN      NaN          NaN NaN
2      NaN          NaN      NaN          NaN NaN
3      NaN          NaN      NaN          NaN NaN
4      NaN          NaN      NaN          NaN NaN
       id             name position abbreviation   0
0  8094.0  Korhonen, Mikko    OTHER          KOR NaN
1     NaN              NaN      NaN          NaN NaN
2     NaN              NaN      NaN          NaN NaN
3     NaN              NaN      NaN          NaN NaN
4     NaN              NaN      NaN          NaN NaN
        id             name position abbreviation   0
0  86545.0  Saddier, Adrien    OTHER          SAD NaN
1      NaN              NaN      NaN          NaN NaN
2      NaN              NaN      NaN          NaN NaN
3      NaN              NaN      NaN          NaN NaN
4      NaN              NaN      NaN          NaN NaN
        id           name position abbreviation   0
0  86591.0  Wiebe, Gunner    OTHER          WIE NaN
1      NaN            NaN      NaN          NaN NaN
2      NaN            NaN      NaN          NaN NaN
3      NaN            NaN      NaN          NaN NaN
4      NaN            NaN      NaN          NaN NaN
        id             name position abbreviation   0
0  86574.0  Gumberg, Jordan    OTHER          GUM NaN
1      NaN              NaN      NaN          NaN NaN
2      NaN              NaN      NaN          NaN NaN
3      NaN              NaN      NaN          NaN NaN
4      NaN              NaN      NaN          NaN NaN
        id          name position abbreviation   0
0  86598.0  Penge, Marco    OTHER          PEN NaN
1      NaN           NaN      NaN          NaN NaN
2      NaN           NaN      NaN          NaN NaN
3      NaN           NaN      NaN          NaN NaN
4      NaN           NaN      NaN          NaN NaN
       id                name position abbreviation   0
0  8114.0  Laporta, Francesco    OTHER          LAP NaN
1     NaN                 NaN      NaN          NaN NaN
2     NaN                 NaN      NaN          NaN NaN
3     NaN                 NaN      NaN          NaN NaN
4     NaN                 NaN      NaN          NaN NaN
        id            name position abbreviation   0
0  86582.0  Hidalgo, Angel    OTHER          HID NaN
1      NaN             NaN      NaN          NaN NaN
2      NaN             NaN      NaN          NaN NaN
3      NaN             NaN      NaN          NaN NaN
4      NaN             NaN      NaN          NaN NaN
       id              name position abbreviation   0
0  8132.0  Migliozzi, Guido    OTHER          MIG NaN
1     NaN               NaN      NaN          NaN NaN
2     NaN               NaN      NaN          NaN NaN
3     NaN               NaN      NaN          NaN NaN
4     NaN               NaN      NaN          NaN NaN
        id            name position abbreviation   0
0  86577.0  Clements, Todd    OTHER          CLE NaN
1      NaN             NaN      NaN          NaN NaN
2      NaN             NaN      NaN          NaN NaN
3      NaN             NaN      NaN          NaN NaN
4      NaN             NaN      NaN          NaN NaN
       id          name position abbreviation   0
0  8092.0  Fisher, Ross    OTHER          FIS NaN
1     NaN           NaN      NaN          NaN NaN
2     NaN           NaN      NaN          NaN NaN
3     NaN           NaN      NaN          NaN NaN
4     NaN           NaN      NaN          NaN NaN
       id               name position abbreviation   0
0  8099.0  Zanotti, Fabrizio    OTHER          ZAN NaN
1     NaN                NaN      NaN          NaN NaN
2     NaN                NaN      NaN          NaN NaN
3     NaN                NaN      NaN          NaN NaN
4     NaN                NaN      NaN          NaN NaN
        id                name position abbreviation   0
0  86607.0  Christensen, Tiger    OTHER          CHR NaN
1      NaN                 NaN      NaN          NaN NaN
2      NaN                 NaN      NaN          NaN NaN
3      NaN                 NaN      NaN          NaN NaN
4      NaN                 NaN      NaN          NaN NaN
       id            name position abbreviation   0
0  8111.0  Canter, Laurie    OTHER          CAN NaN
1     NaN             NaN      NaN          NaN NaN
2     NaN             NaN      NaN          NaN NaN
3     NaN             NaN      NaN          NaN NaN
4     NaN             NaN      NaN          NaN NaN
       id               name position abbreviation   0
0  8107.0  Green, Gavin Kyle    OTHER          GRE NaN
1     NaN                NaN      NaN          NaN NaN
2     NaN                NaN      NaN          NaN NaN
3     NaN                NaN      NaN          NaN NaN
4     NaN                NaN      NaN          NaN NaN
        id           name position abbreviation   0
0  86556.0  Mruzek, Filip    OTHER          MRU NaN
1      NaN            NaN      NaN          NaN NaN
2      NaN            NaN      NaN          NaN NaN
3      NaN            NaN      NaN          NaN NaN
4      NaN            NaN      NaN          NaN NaN
       id                 name position abbreviation   0
0  8119.0  Broberg, Kristoffer    OTHER          BRO NaN
1     NaN                  NaN      NaN          NaN NaN
2     NaN                  NaN      NaN          NaN NaN
3     NaN                  NaN      NaN          NaN NaN
4     NaN                  NaN      NaN          NaN NaN
        id            name position abbreviation   0
0  86537.0  Whitnell, Dale    OTHER          WHI NaN
1      NaN             NaN      NaN          NaN NaN
2      NaN             NaN      NaN          NaN NaN
3      NaN             NaN      NaN          NaN NaN
4      NaN             NaN      NaN          NaN NaN
        id                       name position abbreviation   0
0  86570.0  Moeller, Niklas Noergaard    OTHER          MOE NaN
1      NaN                        NaN      NaN          NaN NaN
2      NaN                        NaN      NaN          NaN NaN
3      NaN                        NaN      NaN          NaN NaN
4      NaN                        NaN      NaN          NaN NaN
       id             name position abbreviation   0
0  8085.0  McEvoy, Richard    OTHER          MCE NaN
1     NaN              NaN      NaN          NaN NaN
2     NaN              NaN      NaN          NaN NaN
3     NaN              NaN      NaN          NaN NaN
4     NaN              NaN      NaN          NaN NaN
        id              name position abbreviation   0
0  86616.0  De Bruyn, Jannik    OTHER           DE NaN
1      NaN               NaN      NaN          NaN NaN
2      NaN               NaN      NaN          NaN NaN
3      NaN               NaN      NaN          NaN NaN
4      NaN               NaN      NaN          NaN NaN
        id           name position abbreviation   0
0  86624.0  Siemens, Carl    OTHER          SIE NaN
1      NaN            NaN      NaN          NaN NaN
2      NaN            NaN      NaN          NaN NaN
3      NaN            NaN      NaN          NaN NaN
4      NaN            NaN      NaN          NaN NaN
       id                  name position abbreviation   0
0  8264.0  Schaper, Jayden Trey    OTHER          SCH NaN
1     NaN                   NaN      NaN          NaN NaN
2     NaN                   NaN      NaN          NaN NaN
3     NaN                   NaN      NaN          NaN NaN
4     NaN                   NaN      NaN          NaN NaN
        id           name position abbreviation   0
0  86614.0  Berry, Joshua    OTHER          BER NaN
1      NaN            NaN      NaN          NaN NaN
2      NaN            NaN      NaN          NaN NaN
3      NaN            NaN      NaN          NaN NaN
4      NaN            NaN      NaN          NaN NaN
        id              name position abbreviation   0
0  86606.0  Bradbury, Daniel    OTHER          BRA NaN
1      NaN               NaN      NaN          NaN NaN
2      NaN               NaN      NaN          NaN NaN
3      NaN               NaN      NaN          NaN NaN
4      NaN               NaN      NaN          NaN NaN

        id             name position abbreviation   0
0  86621.0  Schutz, Yannick    OTHER          SCH NaN
1      NaN              NaN      NaN          NaN NaN
2      NaN              NaN      NaN          NaN NaN
3      NaN              NaN      NaN          NaN NaN
4      NaN              NaN      NaN          NaN NaN
        id             name position abbreviation   0
0  86538.0  De Jager, Louis    OTHER           DE NaN
1      NaN              NaN      NaN          NaN NaN
2      NaN              NaN      NaN          NaN NaN
3      NaN              NaN      NaN          NaN NaN
4      NaN              NaN      NaN          NaN NaN
       id              name position abbreviation   0
0  8082.0  Donaldson, Jamie    OTHER          DON NaN
1     NaN               NaN      NaN          NaN NaN
2     NaN               NaN      NaN          NaN NaN
3     NaN               NaN      NaN          NaN NaN
4     NaN               NaN      NaN          NaN NaN
       id          name position abbreviation   0
0  3586.0  Waring, Paul    OTHER          WAR NaN
1     NaN           NaN      NaN          NaN NaN
2     NaN           NaN      NaN          NaN NaN
3     NaN           NaN      NaN          NaN NaN
4     NaN           NaN      NaN          NaN NaN
        id           name position abbreviation   0
0  86547.0  Huizing, Daan    OTHER          HUI NaN
1      NaN            NaN      NaN          NaN NaN
2      NaN            NaN      NaN          NaN NaN
3      NaN            NaN      NaN          NaN NaN
4      NaN            NaN      NaN          NaN NaN
       id        name position abbreviation   0
0  3348.0  Lewis, Tom    OTHER          LEW NaN
1     NaN         NaN      NaN          NaN NaN
2     NaN         NaN      NaN          NaN NaN
3     NaN         NaN      NaN          NaN NaN
4     NaN         NaN      NaN          NaN NaN
       id         name position abbreviation   0
0  3427.0  Li, Haotong    OTHER          LIH NaN
1     NaN          NaN      NaN          NaN NaN
2     NaN          NaN      NaN          NaN NaN
3     NaN          NaN      NaN          NaN NaN
4     NaN          NaN      NaN          NaN NaN
       id           name position abbreviation   0
0  8130.0  Elvira, Nacho    OTHER          ELV NaN
1     NaN            NaN      NaN          NaN NaN
2     NaN            NaN      NaN          NaN NaN
3     NaN            NaN      NaN          NaN NaN
4     NaN            NaN      NaN          NaN NaN
        id            name position abbreviation   0
0  86601.0  Celli, Filippo    OTHER          CEL NaN
1      NaN             NaN      NaN          NaN NaN
2      NaN             NaN      NaN          NaN NaN
3      NaN             NaN      NaN          NaN NaN
4      NaN             NaN      NaN          NaN NaN
       id             name position abbreviation   0
0  8127.0  Lombard, Zander    OTHER          LOM NaN
1     NaN              NaN      NaN          NaN NaN
2     NaN              NaN      NaN          NaN NaN
3     NaN              NaN      NaN          NaN NaN
4     NaN              NaN      NaN          NaN NaN
        id         name position abbreviation   0
0  86544.0  Enoch, Rhys    OTHER          ENO NaN
1      NaN          NaN      NaN          NaN NaN
2      NaN          NaN      NaN          NaN NaN
3      NaN          NaN      NaN          NaN NaN
4      NaN          NaN      NaN          NaN NaN
        id                         name position abbreviation   0
0  86568.0  Johannessen, Kristian Krogh    OTHER          JOH NaN
1      NaN                          NaN      NaN          NaN NaN
2      NaN                          NaN      NaN          NaN NaN
3      NaN                          NaN      NaN          NaN NaN
4      NaN                          NaN      NaN          NaN NaN
        id             name position abbreviation   0
0  86576.0  Williams, Robin    OTHER          WIL NaN
1      NaN              NaN      NaN          NaN NaN
2      NaN              NaN      NaN          NaN NaN
3      NaN              NaN      NaN          NaN NaN
4      NaN              NaN      NaN          NaN NaN
        id             name position abbreviation   0
0  86593.0  Jordan, Matthew    OTHER          JOR NaN
1      NaN              NaN      NaN          NaN NaN
2      NaN              NaN      NaN          NaN NaN
3      NaN              NaN      NaN          NaN NaN
4      NaN              NaN      NaN          NaN NaN
        id               name position abbreviation   0
0  86745.0  Fitzpatrick, Alex    OTHER          FIT NaN
1      NaN                NaN      NaN          NaN NaN
2      NaN                NaN      NaN          NaN NaN
3      NaN                NaN      NaN          NaN NaN
4      NaN                NaN      NaN          NaN NaN
        id       name position abbreviation   0
0  86572.0  Dean, Joe    OTHER          DEA NaN
1      NaN        NaN      NaN          NaN NaN
2      NaN        NaN      NaN          NaN NaN
3      NaN        NaN      NaN          NaN NaN
4      NaN        NaN      NaN          NaN NaN
       id                   name position abbreviation   0
0  3310.0  Cabrera Bello, Rafael    OTHER          CAB NaN
1     NaN                    NaN      NaN          NaN NaN
2     NaN                    NaN      NaN          NaN NaN
3     NaN                    NaN      NaN          NaN NaN
4     NaN                    NaN      NaN          NaN NaN
       id               name position abbreviation   0
0  7596.0  Molinari, Edoardo    OTHER          MOL NaN
1     NaN                NaN      NaN          NaN NaN
2     NaN                NaN      NaN          NaN NaN
3     NaN                NaN      NaN          NaN NaN
4     NaN                NaN      NaN          NaN NaN
        id             name position abbreviation   0
0  86548.0  Rusch, Benjamin    OTHER          RUS NaN
1      NaN              NaN      NaN          NaN NaN
2      NaN              NaN      NaN          NaN NaN
3      NaN              NaN      NaN          NaN NaN
4      NaN              NaN      NaN          NaN NaN
        id            name position abbreviation   0
0  86567.0  Prinsloo, Jaco    OTHER          PRI NaN
1      NaN             NaN      NaN          NaN NaN
2      NaN             NaN      NaN          NaN NaN
3      NaN             NaN      NaN          NaN NaN
4      NaN             NaN      NaN          NaN NaN

In [153]:
target_df = []

In [150]:
temp_df.count()

participants    15
id              15
dtype: int64

In [146]:
temp_df = df[["participants", "id"]]

In [165]:
len(temp_df)

15

In [169]:
len(temp_df['participants'])

15

In [191]:
flattened_data = []
ids = []

In [284]:

combined_list = []
for index, row in df.iterrows():
    list_in_cell = row["participants"]
    #print(len(list_in_cell))
    for dictionary in list_in_cell:
        #print(dictionary, "----------------", index)
        dictionary['match_id'] = df['id'][index]
        combined_list.extend(list_in_cell)



participant_df = pd.DataFrame(combined_list)

In [285]:
participant_df = participant_df.drop_duplicates(subset=['id', 'match_id'], keep = 'last')

In [286]:
participant_df

          id                     name position abbreviation  match_id
24492  86605             Hammer, Marc    OTHER          HAM    816775
24493  86608  Friedrichsen, Sebastian    OTHER          FRI    816775
24494  86742             Paul, Yannik    OTHER          PAU    816775
24495  86743            McKibbin, Tom    OTHER          MCK    816775
24496   3324        Wiesberger, Bernd    OTHER          WIE    816775
...      ...                      ...      ...          ...       ...
49050     97    Tokyo Yakult Swallows     AWAY          TYS    818641
49053   8188        Oberleitner, Neil     HOME          OBE    819086
49054   2348        Matusevich, Anton     AWAY          MAT    819086
49057  34668     Heidelberg United FC     HOME          HDB    817874
49058  34478        Dandenong Thunder     AWAY          DAN    817874

[347 rows x 5 columns]

In [287]:
participant_df = participant_df.rename(columns={col: f'participant_{col}' for col in participant_df.columns if col != 'match_id'}) # Merge the new DataFrame with the original DataFrame 
merged_df = df.drop(columns=['participants']).merge(participant_df, left_on='id', right_on='match_id') # Drop the 'match_id' column if it's no longer needed 
merged_df = merged_df.drop(columns=['match_id'])

In [288]:
merged_df

,id,startTime,messageTime,sportType,matchState,status,marketCount,group,markets,eventType,...,eventTags,score,gameClock,sportCurrentGameState,eventMetadata,aggregatedEventPoints,participant_id,participant_name,participant_position,participant_abbreviation
0,816775,2024-05-29T00:00:00Z,2024-05-31T11:00:31.228Z,GOLF,ONGOING,RUNNING,1,"{'id': 9041, 'name': 'European Open (DP World ...",[{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666'...,OUTRIGHT,...,"[blockedOutright, venueStateLocation:UNKNOWN, ...",NaN,NaN,NaN,NaN,NaN,86605,"Hammer, Marc",OTHER,HAM
1,816775,2024-05-29T00:00:00Z,2024-05-31T11:00:31.228Z,GOLF,ONGOING,RUNNING,1,"{'id': 9041, 'name': 'European Open (DP World ...",[{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666'...,OUTRIGHT,...,"[blockedOutright, venueStateLocation:UNKNOWN, ...",NaN,NaN,NaN,NaN,NaN,86608,"Friedrichsen, Sebastian",OTHER,FRI
2,816775,2024-05-29T00:00:00Z,2024-05-31T11:00:31.228Z,GOLF,ONGOING,RUNNING,1,"{'id': 9041, 'name': 'European Open (DP World ...",[{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666'...,OUTRIGHT,...,"[blockedOutright, venueStateLocation:UNKNOWN, ...",NaN,NaN,NaN,NaN,NaN,86742,"Paul, Yannik",OTHER,PAU
3,816775,2024-05-29T00:00:00Z,2024-05-31T11:00:31.228Z,GOLF,ONGOING,RUNNING,1,"{'id': 9041, 'name': 'European Open (DP World ...",[{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666'...,OUTRIGHT,...,"[blockedOutright, venueStateLocation:UNKNOWN, ...",NaN,NaN,NaN,NaN,NaN,86743,"McKibbin, Tom",OTHER,MCK
4,816775,2024-05-29T00:00:00Z,2024-05-31T11:00:31.228Z,GOLF,ONGOING,RUNNING,1,"{'id': 9041, 'name': 'European Open (DP World ...",[{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666'...,OUTRIGHT,...,"[blockedOutright, venueStateLocation:UNKNOWN, ...",NaN,NaN,NaN,NaN,NaN,3324,"Wiesberger, Bernd",OTHER,WIE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342,818641,2024-05-31T09:00:00Z,2024-05-31T11:02:13.996Z,BASEBALL,ONGOING,RUNNING,9,"{'id': 52, 'name': 'Japan - Nippon Professiona...",[{'id': '31c6f3d1-492c-3490-842d-88cb30455f53'...,MATCH,...,"[awayParticipantStateLocation:OTHER, venueStat...","{'total': {'home': {'value': 1}, 'away': {'val...","{'clockType': 'SECTIONS', 'eventState': 'RUNNI...","{'updatedAt': '1717153333764', 'baseballCurren...",NaN,NaN,97,Tokyo Yakult Swallows,AWAY,TYS
343,819086,2024-05-31T09:10:00Z,2024-05-31T11:02:11.463Z,TENNIS,ONGOING,RUNNING,22,"{'id': 4527, 'name': 'ITF Slovenia F3 (M)', 'p...",[{'id': 'f5e39123-3a38-3c12-8a2d-3e619e340f7e'...,MATCH,...,"[awayParticipantStateLocation:OTHER, venueStat...","{'total': {'home': {'sets': 1, 'games': 1, 'po...","{'clockType': 'SECTIONS', 'eventState': 'RUNNI...","{'updatedAt': '0', 'netSportCurrentGameState':...",NaN,NaN,8188,"Oberleitner, Neil",HOME,OBE
344,819086,2024-05-31T09:10:00Z,2024-05-31T11:02:11.463Z,TENNIS,ONGOING,RUNNING,22,"{'id': 4527, 'name': 'ITF Slovenia F3 (M)', 'p...",[{'id': 'f5e39123-3a38-3c12-8a2d-3e619e340f7e'...,MATCH,...,"[awayParticipantStateLocation:OTHER, venueStat...","{'total': {'home': {'sets': 1, 'games': 1, 'po...","{'clockType': 'SECTIONS', 'eventState': 'RUNNI...","{'updatedAt': '0', 'netSportCurrentGameState':...",NaN,NaN,2348,"Matusevich, Anton",AWAY,MAT
345,817874,2024-05-31T09:15:00Z,2024-05-31T11:02:01.298Z,FOOTBALL,ONGOING,RUNNING,4,"{'id': 3942, 'name': 'Australia - Victoria, NP...",[{'id': '626bc6bc-1d2a-3bfb-b908-df7ac028d575'...,MATCH,...,"[sgp-pre, awayParticipantStateLocation:OTHER, ...","{'total': {'home': {'value': 2}, 'away': {'val...","{'clockType': 'STOPWATCH', 'eventState': 'RUNN...",NaN,NaN,"{'total': {'home': {'CORNER': 4, 'YELLOW_CARD'...",34668,Heidelberg United FC,HOME,HDB
346,817874,2024-05-31T09:15:00Z,2024-05-31T11:02:01.298Z,FOOTBALL,ONGOING,RUNNING,4,"{'id': 3942, 'name': 'Australia - Victoria, NP...",[{'id': '626bc6bc-1d2a-3bfb-b908-df7ac028d575'...,MATCH,...,"[sgp-pre, awayParticipantStateLocation:OTHER, ...","{'total': {'home': {'value': 2}, 'away': {'val...","{'clockType': 'STOPWATCH', 'eventState': 'RUNN...",NaN,NaN,"{'total': {'home': {'CORNER': 4, 'YELLOW_CARD'...",34478,Dandenong Thunder,AWAY,DAN

In [292]:
df['eventDetails']

0     {'block_cashout': 'false', 'longTermEventType'...
1     {'subgroupNameKey': 'French Open Women Doubles...
2     {'subgroupNameKey': 'French Open Women Doubles...
3     {'block_cashout': 'false', 'longTermEventType'...
4     {'subgroupNameKey': 'ATP Challenger Vicenza, I...
5     {'block_cashout': 'false', 'longTermEventType'...
6     {'block_cashout': 'false', 'longTermEventType'...
7     {'subgroupNameKey': 'French Open Women Singles...
8     {'subgroupNameKey': 'Professional Baseball, In...
9     {'subgroupNameKey': 'French Open Women Doubles...
10    {'subgroupNameKey': 'Professional Baseball, In...
11    {'subgroupNameKey': 'Professional Baseball, In...
12    {'subgroupNameKey': 'Professional Baseball, In...
13    {'subgroupNameKey': 'Professional Baseball, In...
14    {'subgroupNameKey': 'ITF Slovenia F3, Men Sing...
15    {'subgroupNameKey': 'ITF Romania F4, Men Singl...
16    {'subgroupNameKey': 'KBO League', 'block_casho...
17    {'subgroupNameKey': 'KBO League', 'block_casho...
Name: eventDetails, dtype: object

In [293]:
eventDetails_df = df['eventDetails'].apply(pd.Series)

In [294]:
eventDetails_df

,block_cashout,longTermEventType,outrightType,subgroupNameKey,best_of_sets,activeParticipant,subgroupIdKey
0,false,COMPETITION_GROUP,stage,NaN,NaN,NaN,NaN
1,false,NaN,NaN,"French Open Women Doubles, Round_of_64",3,AWAY,141672
2,false,NaN,NaN,"French Open Women Doubles, Round_of_64",3,HOME,141672
3,false,COMPETITION_GROUP,stage,NaN,NaN,NaN,NaN
4,false,NaN,NaN,"ATP Challenger Vicenza, Italy Men Singles, Rou...",3,AWAY,147401
5,false,COMPETITION_GROUP,competition_group,NaN,NaN,NaN,NaN
6,false,COMPETITION_GROUP,competition_group,NaN,NaN,NaN,NaN
7,false,NaN,NaN,"French Open Women Singles, Round_of_32",3,AWAY,132845
8,false,NaN,NaN,"Professional Baseball, Interleague",NaN,NaN,20546
9,false,NaN,NaN,"French Open Women Doubles, Round_of_64",3,HOME,141672
10,false,NaN,NaN,"Professional Baseball, Interleague",NaN,NaN,20546
11,false,NaN,NaN,"Professional Baseball, Interleague",NaN,NaN,20546
12,false,NaN,NaN,"Professional Baseball, Interleague",NaN,NaN,20546
13,false,NaN,NaN,"Professional Baseball, Interleague",NaN,NaN,20546
14,false,NaN,NaN,"ITF Slovenia F3, Men Singles, Quarterfinal",3,AWAY,149935
15,false,NaN,NaN,"ITF Romania F4, Men Singles, Quarterfinal",3,AWAY,149977
16,false,NaN,NaN,KBO League,NaN,NaN,4395
17,true,NaN,NaN,KBO League,NaN,NaN,4395

In [295]:
eventDetails_df['match_id'] = df['id']

In [296]:
eventDetails_df

,block_cashout,longTermEventType,outrightType,subgroupNameKey,best_of_sets,activeParticipant,subgroupIdKey,match_id
0,false,COMPETITION_GROUP,stage,NaN,NaN,NaN,NaN,816775
1,false,NaN,NaN,"French Open Women Doubles, Round_of_64",3,AWAY,141672,814918
2,false,NaN,NaN,"French Open Women Doubles, Round_of_64",3,HOME,141672,814933
3,false,COMPETITION_GROUP,stage,NaN,NaN,NaN,NaN,816776
4,false,NaN,NaN,"ATP Challenger Vicenza, Italy Men Singles, Rou...",3,AWAY,147401,817801
5,false,COMPETITION_GROUP,competition_group,NaN,NaN,NaN,NaN,819146
6,false,COMPETITION_GROUP,competition_group,NaN,NaN,NaN,NaN,819147
7,false,NaN,NaN,"French Open Women Singles, Round_of_32",3,AWAY,132845,818856
8,false,NaN,NaN,"Professional Baseball, Interleague",NaN,NaN,20546,818646
9,false,NaN,NaN,"French Open Women Doubles, Round_of_64",3,HOME,141672,814921
10,false,NaN,NaN,"Professional Baseball, Interleague",NaN,NaN,20546,818645
11,false,NaN,NaN,"Professional Baseball, Interleague",NaN,NaN,20546,818644
12,false,NaN,NaN,"Professional Baseball, Interleague",NaN,NaN,20546,818642
13,false,NaN,NaN,"Professional Baseball, Interleague",NaN,NaN,20546,818641
14,false,NaN,NaN,"ITF Slovenia F3, Men Singles, Quarterfinal",3,AWAY,149935,819086
15,false,NaN,NaN,"ITF Romania F4, Men Singles, Quarterfinal",3,AWAY,149977,819044
16,false,NaN,NaN,KBO League,NaN,NaN,4395,818688
17,true,NaN,NaN,KBO League,NaN,NaN,4395,818695

In [264]:
eventDetails_df = eventDetails_df.rename(columns={col: f'eventDetails_{col}' for col in eventDetails_df.columns if col != 'match_id'}) # Merge the new DataFrame with the original DataFrame 
merged_df = merged_df.drop(columns=['eventDetails']).merge(eventDetails_df, left_on='id', right_on='match_id') # Drop the 'match_id' column if it's no longer needed 
merged_df = merged_df.drop(columns=['match_id'])

In [265]:
merged_df

,id,startTime,messageTime,sportType,matchState,status,marketCount,group,markets,eventType,...,participant_position,participant_abbreviation,eventDetails_block_cashout,eventDetails_longTermEventType,eventDetails_outrightType,eventDetails_subgroupNameKey,eventDetails_best_of_sets,eventDetails_activeParticipant,eventDetails_subgroupIdKey,eventDetails_tiebreak
0,816775,2024-05-29T00:00:00Z,2024-05-31T05:48:54.645Z,GOLF,ONGOING,RUNNING,1,"{'id': 9041, 'name': 'European Open 2024', 'pa...",[{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666'...,OUTRIGHT,...,OTHER,HAM,false,COMPETITION_GROUP,stage,NaN,NaN,NaN,NaN,NaN
1,816775,2024-05-29T00:00:00Z,2024-05-31T05:48:54.645Z,GOLF,ONGOING,RUNNING,1,"{'id': 9041, 'name': 'European Open 2024', 'pa...",[{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666'...,OUTRIGHT,...,OTHER,FRI,false,COMPETITION_GROUP,stage,NaN,NaN,NaN,NaN,NaN
2,816775,2024-05-29T00:00:00Z,2024-05-31T05:48:54.645Z,GOLF,ONGOING,RUNNING,1,"{'id': 9041, 'name': 'European Open 2024', 'pa...",[{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666'...,OUTRIGHT,...,OTHER,PAU,false,COMPETITION_GROUP,stage,NaN,NaN,NaN,NaN,NaN
3,816775,2024-05-29T00:00:00Z,2024-05-31T05:48:54.645Z,GOLF,ONGOING,RUNNING,1,"{'id': 9041, 'name': 'European Open 2024', 'pa...",[{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666'...,OUTRIGHT,...,OTHER,MCK,false,COMPETITION_GROUP,stage,NaN,NaN,NaN,NaN,NaN
4,816775,2024-05-29T00:00:00Z,2024-05-31T05:48:54.645Z,GOLF,ONGOING,RUNNING,1,"{'id': 9041, 'name': 'European Open 2024', 'pa...",[{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666'...,OUTRIGHT,...,OTHER,WIE,false,COMPETITION_GROUP,stage,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,819229,2024-05-31T07:30:00Z,2024-05-31T08:18:57.806Z,BASKETBALL,ONGOING,RUNNING,12,"{'id': 4087, 'name': 'New Zealand - NBL', 'par...",[{'id': '9bc7c8c2-db15-386f-aa0e-3f87d536d876'...,MATCH,...,AWAY,OTA,false,NaN,NaN,NBL,NaN,NaN,3077,NaN
187,818873,2024-05-31T07:50:00Z,2024-05-31T08:18:40.524Z,TENNIS,ONGOING,RUNNING,37,"{'id': 9031, 'name': 'ITF Croatia F10 (M)', 'p...",[{'id': 'd2d60c43-942a-375b-b989-99df804d4620'...,MATCH,...,HOME,BIE,false,NaN,NaN,"ITF Croatia F10, Men Singles, Quarterfinal",3,AWAY,149961,NaN
188,818873,2024-05-31T07:50:00Z,2024-05-31T08:18:40.524Z,TENNIS,ONGOING,RUNNING,37,"{'id': 9031, 'name': 'ITF Croatia F10 (M)', 'p...",[{'id': 'd2d60c43-942a-375b-b989-99df804d4620'...,MATCH,...,AWAY,MAS,false,NaN,NaN,"ITF Croatia F10, Men Singles, Quarterfinal",3,AWAY,149961,NaN
189,819082,2024-05-31T07:55:00Z,2024-05-31T08:18:54.369Z,TABLE_TENNIS,ONGOING,RUNNING,10,"{'id': 9052, 'name': 'WTT Champions Chongqing,...",[{'id': '65a9e2c5-f31b-38ea-9917-66b3eab7b141'...,MATCH,...,HOME,POL,false,NaN,NaN,"WTT Champions Chongqing, WS, Round of 32",5,NaN,150533,NaN
190,819082,2024-05-31T07:55:00Z,2024-05-31T08:18:54.369Z,TABLE_TENNIS,ONGOING,RUNNING,10,"{'id': 9052, 'name': 'WTT Champions Chongqing,...",[{'id': '65a9e2c5-f31b-38ea-9917-66b3eab7b141'...,MATCH,...,AWAY,WAN,false,NaN,NaN,"WTT Champions Chongqing, WS, Round of 32",5,NaN,150533,NaN

In [268]:
def flatten_dict(d, parent_key='', sep='_'):
    items = []
    for k, v in d.items():
        new_key = f"{parent_key}{sep}{k}" if parent_key else k
        if isinstance(v, dict):
            items.extend(flatten_dict(v, new_key, sep=sep).items())
        else:
            items.append((new_key, v))
    return dict(items)

In [269]:
def get_group(df, column_name, prefix):
    temp_df = df[[column_name, 'id']]
    combined_list = []
    for index, row in temp_df.iterrows():
        nested_dict = row[column_name]
        if isinstance(nested_dict, dict):
            nested_dict_flat = flatten_dict(nested_dict)
            nested_dict_flat['match_id'] = temp_df['id'][index]
            combined_list.append(nested_dict_flat)
    
    group_df = pd.DataFrame(combined_list)
    # Rename columns except 'match_id'
    group_df = group_df.rename(columns={col: f'{prefix}_{col}' if col != 'match_id' else col for col in group_df.columns})
    
    # Ensure no duplicates in the new DataFrame using both 'group_id' (renamed) and 'match_id'
    group_df = group_df.drop_duplicates(subset=[f'{prefix}_id', 'match_id'])
#group_df = get_group(df, 'group', 'group')

# Drop the original nested column from the original DataFrame
    df = df.drop(columns=['group'])

    # Merge the extracted DataFrame back into the original DataFrame
    merged_df = df.merge(group_df, left_on='id', right_on='match_id').drop(columns=['match_id'])

    
    return merged_df

In [270]:
merged_df

,id,startTime,messageTime,sportType,matchState,status,marketCount,group,markets,eventType,...,participant_position,participant_abbreviation,eventDetails_block_cashout,eventDetails_longTermEventType,eventDetails_outrightType,eventDetails_subgroupNameKey,eventDetails_best_of_sets,eventDetails_activeParticipant,eventDetails_subgroupIdKey,eventDetails_tiebreak
0,816775,2024-05-29T00:00:00Z,2024-05-31T05:48:54.645Z,GOLF,ONGOING,RUNNING,1,"{'id': 9041, 'name': 'European Open 2024', 'pa...",[{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666'...,OUTRIGHT,...,OTHER,HAM,false,COMPETITION_GROUP,stage,NaN,NaN,NaN,NaN,NaN
1,816775,2024-05-29T00:00:00Z,2024-05-31T05:48:54.645Z,GOLF,ONGOING,RUNNING,1,"{'id': 9041, 'name': 'European Open 2024', 'pa...",[{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666'...,OUTRIGHT,...,OTHER,FRI,false,COMPETITION_GROUP,stage,NaN,NaN,NaN,NaN,NaN
2,816775,2024-05-29T00:00:00Z,2024-05-31T05:48:54.645Z,GOLF,ONGOING,RUNNING,1,"{'id': 9041, 'name': 'European Open 2024', 'pa...",[{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666'...,OUTRIGHT,...,OTHER,PAU,false,COMPETITION_GROUP,stage,NaN,NaN,NaN,NaN,NaN
3,816775,2024-05-29T00:00:00Z,2024-05-31T05:48:54.645Z,GOLF,ONGOING,RUNNING,1,"{'id': 9041, 'name': 'European Open 2024', 'pa...",[{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666'...,OUTRIGHT,...,OTHER,MCK,false,COMPETITION_GROUP,stage,NaN,NaN,NaN,NaN,NaN
4,816775,2024-05-29T00:00:00Z,2024-05-31T05:48:54.645Z,GOLF,ONGOING,RUNNING,1,"{'id': 9041, 'name': 'European Open 2024', 'pa...",[{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666'...,OUTRIGHT,...,OTHER,WIE,false,COMPETITION_GROUP,stage,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,819229,2024-05-31T07:30:00Z,2024-05-31T08:18:57.806Z,BASKETBALL,ONGOING,RUNNING,12,"{'id': 4087, 'name': 'New Zealand - NBL', 'par...",[{'id': '9bc7c8c2-db15-386f-aa0e-3f87d536d876'...,MATCH,...,AWAY,OTA,false,NaN,NaN,NBL,NaN,NaN,3077,NaN
187,818873,2024-05-31T07:50:00Z,2024-05-31T08:18:40.524Z,TENNIS,ONGOING,RUNNING,37,"{'id': 9031, 'name': 'ITF Croatia F10 (M)', 'p...",[{'id': 'd2d60c43-942a-375b-b989-99df804d4620'...,MATCH,...,HOME,BIE,false,NaN,NaN,"ITF Croatia F10, Men Singles, Quarterfinal",3,AWAY,149961,NaN
188,818873,2024-05-31T07:50:00Z,2024-05-31T08:18:40.524Z,TENNIS,ONGOING,RUNNING,37,"{'id': 9031, 'name': 'ITF Croatia F10 (M)', 'p...",[{'id': 'd2d60c43-942a-375b-b989-99df804d4620'...,MATCH,...,AWAY,MAS,false,NaN,NaN,"ITF Croatia F10, Men Singles, Quarterfinal",3,AWAY,149961,NaN
189,819082,2024-05-31T07:55:00Z,2024-05-31T08:18:54.369Z,TABLE_TENNIS,ONGOING,RUNNING,10,"{'id': 9052, 'name': 'WTT Champions Chongqing,...",[{'id': '65a9e2c5-f31b-38ea-9917-66b3eab7b141'...,MATCH,...,HOME,POL,false,NaN,NaN,"WTT Champions Chongqing, WS, Round of 32",5,NaN,150533,NaN
190,819082,2024-05-31T07:55:00Z,2024-05-31T08:18:54.369Z,TABLE_TENNIS,ONGOING,RUNNING,10,"{'id': 9052, 'name': 'WTT Champions Chongqing,...",[{'id': '65a9e2c5-f31b-38ea-9917-66b3eab7b141'...,MATCH,...,AWAY,WAN,false,NaN,NaN,"WTT Champions Chongqing, WS, Round of 32",5,NaN,150533,NaN

In [271]:
merged_df = get_group(merged_df, 'group', 'group')

In [275]:
merged_df

,id,startTime,messageTime,sportType,matchState,status,marketCount,markets,eventType,updatesCount,...,eventDetails_best_of_sets,eventDetails_activeParticipant,eventDetails_subgroupIdKey,eventDetails_tiebreak,group_id,group_name,group_parentGroup_id,group_parentGroup_name,group_parentGroup_parentGroup_id,group_parentGroup_parentGroup_name
0,816775,2024-05-29T00:00:00Z,2024-05-31T05:48:54.645Z,GOLF,ONGOING,RUNNING,1,[{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666'...,OUTRIGHT,426,...,NaN,NaN,NaN,NaN,9041,European Open 2024,269,Men,270,Golf
1,816775,2024-05-29T00:00:00Z,2024-05-31T05:48:54.645Z,GOLF,ONGOING,RUNNING,1,[{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666'...,OUTRIGHT,426,...,NaN,NaN,NaN,NaN,9041,European Open 2024,269,Men,270,Golf
2,816775,2024-05-29T00:00:00Z,2024-05-31T05:48:54.645Z,GOLF,ONGOING,RUNNING,1,[{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666'...,OUTRIGHT,426,...,NaN,NaN,NaN,NaN,9041,European Open 2024,269,Men,270,Golf
3,816775,2024-05-29T00:00:00Z,2024-05-31T05:48:54.645Z,GOLF,ONGOING,RUNNING,1,[{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666'...,OUTRIGHT,426,...,NaN,NaN,NaN,NaN,9041,European Open 2024,269,Men,270,Golf
4,816775,2024-05-29T00:00:00Z,2024-05-31T05:48:54.645Z,GOLF,ONGOING,RUNNING,1,[{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666'...,OUTRIGHT,426,...,NaN,NaN,NaN,NaN,9041,European Open 2024,269,Men,270,Golf
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,819229,2024-05-31T07:30:00Z,2024-05-31T08:18:57.806Z,BASKETBALL,ONGOING,RUNNING,12,[{'id': '9bc7c8c2-db15-386f-aa0e-3f87d536d876'...,MATCH,227,...,NaN,NaN,3077,NaN,4087,New Zealand - NBL,4088,New Zealand,39,Basketball
187,818873,2024-05-31T07:50:00Z,2024-05-31T08:18:40.524Z,TENNIS,ONGOING,RUNNING,37,[{'id': 'd2d60c43-942a-375b-b989-99df804d4620'...,MATCH,59,...,3,AWAY,149961,NaN,9031,ITF Croatia F10 (M),109,ITF Men,21,Tennis
188,818873,2024-05-31T07:50:00Z,2024-05-31T08:18:40.524Z,TENNIS,ONGOING,RUNNING,37,[{'id': 'd2d60c43-942a-375b-b989-99df804d4620'...,MATCH,59,...,3,AWAY,149961,NaN,9031,ITF Croatia F10 (M),109,ITF Men,21,Tennis
189,819082,2024-05-31T07:55:00Z,2024-05-31T08:18:54.369Z,TABLE_TENNIS,ONGOING,RUNNING,10,[{'id': '65a9e2c5-f31b-38ea-9917-66b3eab7b141'...,MATCH,139,...,5,NaN,150533,NaN,9052,"WTT Champions Chongqing, WS",1974,International,535,Table Tennis
190,819082,2024-05-31T07:55:00Z,2024-05-31T08:18:54.369Z,TABLE_TENNIS,ONGOING,RUNNING,10,[{'id': '65a9e2c5-f31b-38ea-9917-66b3eab7b141'...,MATCH,139,...,5,NaN,150533,NaN,9052,"WTT Champions Chongqing, WS",1974,International,535,Table Tennis

In [276]:
merged_df.to_csv("merged_except_markets.csv")

In [237]:
merged_df

,id,startTime,messageTime,sportType,matchState,status,marketCount,group,markets,eventType,...,lastModifiedTime,eventTags,score,gameClock,sportCurrentGameState,eventMetadata,participant_id,participant_name,participant_position,participant_abbreviation
0,816775,2024-05-29T00:00:00Z,2024-05-31T05:48:54.645Z,GOLF,ONGOING,RUNNING,1,"{'id': 9041, 'name': 'European Open 2024', 'pa...",[{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666'...,OUTRIGHT,...,2024-05-31T07:44:21.745Z,"[blockedOutright, venueStateLocation:UNKNOWN, ...",NaN,NaN,NaN,NaN,86605,"Hammer, Marc",OTHER,HAM
1,816775,2024-05-29T00:00:00Z,2024-05-31T05:48:54.645Z,GOLF,ONGOING,RUNNING,1,"{'id': 9041, 'name': 'European Open 2024', 'pa...",[{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666'...,OUTRIGHT,...,2024-05-31T07:44:21.745Z,"[blockedOutright, venueStateLocation:UNKNOWN, ...",NaN,NaN,NaN,NaN,86608,"Friedrichsen, Sebastian",OTHER,FRI
2,816775,2024-05-29T00:00:00Z,2024-05-31T05:48:54.645Z,GOLF,ONGOING,RUNNING,1,"{'id': 9041, 'name': 'European Open 2024', 'pa...",[{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666'...,OUTRIGHT,...,2024-05-31T07:44:21.745Z,"[blockedOutright, venueStateLocation:UNKNOWN, ...",NaN,NaN,NaN,NaN,86742,"Paul, Yannik",OTHER,PAU
3,816775,2024-05-29T00:00:00Z,2024-05-31T05:48:54.645Z,GOLF,ONGOING,RUNNING,1,"{'id': 9041, 'name': 'European Open 2024', 'pa...",[{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666'...,OUTRIGHT,...,2024-05-31T07:44:21.745Z,"[blockedOutright, venueStateLocation:UNKNOWN, ...",NaN,NaN,NaN,NaN,86743,"McKibbin, Tom",OTHER,MCK
4,816775,2024-05-29T00:00:00Z,2024-05-31T05:48:54.645Z,GOLF,ONGOING,RUNNING,1,"{'id': 9041, 'name': 'European Open 2024', 'pa...",[{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666'...,OUTRIGHT,...,2024-05-31T07:44:21.745Z,"[blockedOutright, venueStateLocation:UNKNOWN, ...",NaN,NaN,NaN,NaN,3324,"Wiesberger, Bernd",OTHER,WIE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,819229,2024-05-31T07:30:00Z,2024-05-31T08:18:57.806Z,BASKETBALL,ONGOING,RUNNING,12,"{'id': 4087, 'name': 'New Zealand - NBL', 'par...",[{'id': '9bc7c8c2-db15-386f-aa0e-3f87d536d876'...,MATCH,...,2024-05-31T08:18:57.939Z,"[sgp-pre, awayParticipantStateLocation:OTHER, ...","{'total': {'home': {'value': 34}, 'away': {'va...","{'clockType': 'TIMER', 'eventState': 'RUNNING'...",NaN,NaN,36204,Otago Nuggets,AWAY,OTA
187,818873,2024-05-31T07:50:00Z,2024-05-31T08:18:40.524Z,TENNIS,ONGOING,RUNNING,37,"{'id': 9031, 'name': 'ITF Croatia F10 (M)', 'p...",[{'id': 'd2d60c43-942a-375b-b989-99df804d4620'...,MATCH,...,2024-05-31T08:18:40.651Z,"[awayParticipantStateLocation:OTHER, venueStat...","{'total': {'home': {'sets': 0, 'games': 0, 'po...","{'clockType': 'SECTIONS', 'eventState': 'RUNNI...","{'updatedAt': '0', 'netSportCurrentGameState':...",NaN,2377,"Bielinskyi, Viacheslav",HOME,BIE
188,818873,2024-05-31T07:50:00Z,2024-05-31T08:18:40.524Z,TENNIS,ONGOING,RUNNING,37,"{'id': 9031, 'name': 'ITF Croatia F10 (M)', 'p...",[{'id': 'd2d60c43-942a-375b-b989-99df804d4620'...,MATCH,...,2024-05-31T08:18:40.651Z,"[awayParticipantStateLocation:OTHER, venueStat...","{'total': {'home': {'sets': 0, 'games': 0, 'po...","{'clockType': 'SECTIONS', 'eventState': 'RUNNI...","{'updatedAt': '0', 'netSportCurrentGameState':...",NaN,5967,"Mashtakov, Nikita",AWAY,MAS
189,819082,2024-05-31T07:55:00Z,2024-05-31T08:18:54.369Z,TABLE_TENNIS,ONGOING,RUNNING,10,"{'id': 9052, 'name': 'WTT Champions Chongqing,...",[{'id': '65a9e2c5-f31b-38ea-9917-66b3eab7b141'...,MATCH,...,2024-05-31T08:18:54.496Z,"[awayParticipantStateLocation:OTHER, venueStat...","{'total': {'home': {'games': 1}, 'away': {'gam...","{'clockType': 'SECTIONS', 'eventState': 'RUNNI...","{'updatedAt': '0', 'netSportCurrentGameState':...",NaN,19005,"Polcanova, Sofia",HOME,POL
190,819082,2024-05-31T07:55:00Z,2024-05-31T08:18:54.369Z,TABLE_TENNIS,ONGOING,RUNNING,10,"{'id': 9052, 'name': 'WTT Champions Chongqing,...",[{'id': '65a9e2c5-f31b-38ea-9917-66b3eab7b141'...,MATCH,...,2024-05-31T08:18:54.496Z,"[awayParticipantStateLocation:OTHER, venueStat...","{'total': {'home': {'games': 1}, 'away': {'gam...","{'clockType': 'SECTIONS', 'eventState': 'RUNNI...","{'updatedAt': '0', 'netSportCurrentGameState':...",NaN,26803,"Wang, Yidi",AWAY,WAN

In [157]:
target_df

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14]

In [147]:
temp_df

                                         participants      id
0   [{'id': 8098, 'name': 'Larrazabal, Pablo', 'po...  816775
1   [{'id': 71233, 'name': 'Kato M / Kichenok N', ...  814989
2   [{'id': 86144, 'name': 'Jacquemot E / Tan H', ...  814918
3   [{'id': 38216, 'name': 'Johnson L / Mansouri S...  814870
4   [{'id': 78469, 'name': 'Dolehide CA / Krawczyk...  814933
5   [{'id': 94, 'name': 'Koolhof W / Mektic N', 'p...  814872
6   [{'id': 15813, 'name': 'Dellien Velasco, Murke...  817801
7   [{'id': 86509, 'name': 'Deming E / Molnar B E'...  818400
8   [{'id': 86510, 'name': 'Gorzny S / Tien L', 'p...  818390
9   [{'id': 13787, 'name': 'Fever', 'position': 'H...  817355
10  [{'id': 34816, 'name': 'Venezuela (W)', 'posit...  817823
11  [{'id': 60340, 'name': 'Mets', 'position': 'HO...  818124
12  [{'id': 85772, 'name': 'Braves', 'position': '...  818128
13  [{'id': 70152, 'name': 'Zatecka, Ladislav', 'p...  818841
14  [{'id': 76612, 'name': 'Sychra, Martin', 'posi...  818843

In [ ]:
temp_participant_df = temp_df['participants'].apply(pd.Series)

In [110]:
participants_df

,0,1,2,3,4,5,6,7,8,9,...,147,148,149,150,151,152,153,154,155,156
0,"{'id': 8098, 'name': 'Larrazabal, Pablo', 'pos...","{'id': 8114, 'name': 'Laporta, Francesco', 'po...","{'id': 86586, 'name': 'Long, Hurly', 'position...","{'id': 8107, 'name': 'Green, Gavin Kyle', 'pos...","{'id': 3597, 'name': 'Southgate, Matthew', 'po...","{'id': 86596, 'name': 'Enefer, William', 'posi...","{'id': 3596, 'name': 'Pepperell, Eddie', 'posi...","{'id': 86611, 'name': 'Jarvis, Casey', 'positi...","{'id': 86598, 'name': 'Penge, Marco', 'positio...","{'id': 3310, 'name': 'Cabrera Bello, Rafael', ...",...,"{'id': 86585, 'name': 'McKibbin, Tom', 'positi...","{'id': 3333, 'name': 'Willett, Daniel', 'posit...","{'id': 86560, 'name': 'Scalise, Lorenzo', 'pos...","{'id': 86607, 'name': 'Christensen, Tiger', 'p...","{'id': 86621, 'name': 'Schutz, Yannick', 'posi...","{'id': 86535, 'name': 'Figueiredo, Pedro', 'po...","{'id': 8091, 'name': 'Wilson, Oliver', 'positi...","{'id': 86559, 'name': 'Sordet, Clement', 'posi...","{'id': 8120, 'name': 'Stone, Brandon', 'positi...","{'id': 8138, 'name': 'Hill, Callum', 'position..."
1,"{'id': 71233, 'name': 'Kato M / Kichenok N', '...","{'id': 39274, 'name': 'Saville D / Tomljanovic...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"{'id': 86144, 'name': 'Jacquemot E / Tan H', '...","{'id': 30924, 'name': 'Mihalikova T / Noskova ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"{'id': 38216, 'name': 'Johnson L / Mansouri S'...","{'id': 27433, 'name': 'Arneodo R / Weissborn T...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"{'id': 78469, 'name': 'Dolehide CA / Krawczyk ...","{'id': 86146, 'name': 'Gracheva V / Lechemia E...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,"{'id': 94, 'name': 'Koolhof W / Mektic N', 'po...","{'id': 16499, 'name': 'Arends S / Middelkoop M...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,"{'id': 15813, 'name': 'Dellien Velasco, Murkel...","{'id': 468, 'name': 'Travaglia, Stefano', 'pos...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,"{'id': 86509, 'name': 'Deming E / Molnar B E',...","{'id': 86506, 'name': 'Codd K / Tse E', 'posit...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,"{'id': 86510, 'name': 'Gorzny S / Tien L', 'po...","{'id': 86422, 'name': 'Ayeni O A D / Azkara A'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,"{'id': 13787, 'name': 'Fever', 'position': 'HO...","{'id': 637, 'name': 'Storm', 'position': 'AWAY...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,"{'id': 34816, 'name': 'Venezuela (W)', 'positi...","{'id': 34815, 'name': 'Colombia (W)', 'positio...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,"{'id': 60340, 'name': 'Mets', 'position': 'HOM...","{'id': 256, 'name': 'Diamondbacks', 'position'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,"{'id': 85772, 'name': 'Braves', 'position': 'H...","{'id': 60339, 'name': 'Nationals', 'position':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,"{'id': 70152, 'name': 'Zatecka, Ladislav', 'po...","{'id': 68020, 'name': 'Krejci, Richard', 'posi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,"{'id': 76612, 'name': 'Sychra, Martin', 'posit...","{'id': 26156, 'name': 'Hruska, Vaclav', 'posit...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
temp_participant_df =  temp_df[0].apply(pd.Series)

In [182]:
participants_eachone_df = participants_df[0].apply(pd.Series)
participants_eachone_df['match_id'] = df['id']

In [183]:
participants_new_df = participants_df[1].apply(pd.Series)
participants_new_df['match_id'] = df['id']

In [186]:
result_participant_df = pd.concat([participants_eachone_df, participants_new_df])

In [187]:
result_participant_df

       id                               name position abbreviation  match_id
0    8098                  Larrazabal, Pablo    OTHER          LAR    816775
1   71233                Kato M / Kichenok N     HOME          KKI    814989
2   86144                Jacquemot E / Tan H     HOME          JTA    814918
3   38216             Johnson L / Mansouri S     HOME          JMA    814870
4   78469           Dolehide CA / Krawczyk D     HOME          DKR    814933
5      94               Koolhof W / Mektic N     HOME          KME    814872
6   15813  Dellien Velasco, Murkel Alejandro     HOME          DEV    817801
7   86509              Deming E / Molnar B E     HOME          DMO    818400
8   86510                  Gorzny S / Tien L     HOME          GTI    818390
9   13787                              Fever     HOME          IND    817355
10  34816                      Venezuela (W)     HOME          VEN    817823
11  60340                               Mets     HOME          NYM    818124
12  85772                             Braves     HOME          ATL    818128
13  70152                  Zatecka, Ladislav     HOME          ZAT    818841
14  76612                     Sychra, Martin     HOME          SYC    818843
0    8114                 Laporta, Francesco    OTHER          LAP    816775
1   39274          Saville D / Tomljanovic A     AWAY          STO    814989
2   30924           Mihalikova T / Noskova L     AWAY          MNO    814918
3   27433          Arneodo R / Weissborn T-S     AWAY          AWE    814870
4   86146            Gracheva V / Lechemia E     AWAY          GLE    814933
5   16499            Arends S / Middelkoop M     AWAY          AMI    814872
6     468                 Travaglia, Stefano     AWAY          TRA    817801
7   86506                     Codd K / Tse E     AWAY          CTS    818400
8   86422             Ayeni O A D / Azkara A     AWAY          AAZ    818390
9     637                              Storm     AWAY          SEA    817355
10  34815                       Colombia (W)     AWAY          COL    817823
11    256                       Diamondbacks     AWAY          ARI    818124
12  60339                          Nationals     AWAY          WSH    818128
13  68020                    Krejci, Richard     AWAY          KRE    818841
14  26156                     Hruska, Vaclav     AWAY          HRU    818843

In [112]:
participants_eachone_df

       id                               name position abbreviation  match_id
0    8098                  Larrazabal, Pablo    OTHER          LAR    816775
1   71233                Kato M / Kichenok N     HOME          KKI    814989
2   86144                Jacquemot E / Tan H     HOME          JTA    814918
3   38216             Johnson L / Mansouri S     HOME          JMA    814870
4   78469           Dolehide CA / Krawczyk D     HOME          DKR    814933
5      94               Koolhof W / Mektic N     HOME          KME    814872
6   15813  Dellien Velasco, Murkel Alejandro     HOME          DEV    817801
7   86509              Deming E / Molnar B E     HOME          DMO    818400
8   86510                  Gorzny S / Tien L     HOME          GTI    818390
9   13787                              Fever     HOME          IND    817355
10  34816                      Venezuela (W)     HOME          VEN    817823
11  60340                               Mets     HOME          NYM    818124
12  85772                             Braves     HOME          ATL    818128
13  70152                  Zatecka, Ladislav     HOME          ZAT    818841
14  76612                     Sychra, Martin     HOME          SYC    818843

In [113]:
df["group"]

0     {'id': 9041, 'name': 'European Open (DP World ...
1     {'id': 54, 'name': 'French Open Women Doubles'...
2     {'id': 54, 'name': 'French Open Women Doubles'...
3     {'id': 14, 'name': 'French Open Men Doubles', ...
4     {'id': 54, 'name': 'French Open Women Doubles'...
5     {'id': 14, 'name': 'French Open Men Doubles', ...
6     {'id': 4217, 'name': 'ATP Challenger Vicenza',...
7     {'id': 2632, 'name': 'ITF USA 17A Doubles (W)'...
8     {'id': 2170, 'name': 'ITF USA F11 Doubles (M)'...
9     {'id': 77, 'name': 'WNBA', 'parentGroup': {'id...
10    {'id': 3988, 'name': 'Int. Friendly Games (W)'...
11    {'id': 30, 'name': 'MLB', 'parentGroup': {'id'...
12    {'id': 30, 'name': 'MLB', 'parentGroup': {'id'...
13    {'id': 7002, 'name': 'Czech Liga Pro', 'parent...
14    {'id': 7002, 'name': 'Czech Liga Pro', 'parent...
Name: group, dtype: object

In [114]:
group_df = df['group'].apply(pd.Series)

In [115]:
group_df

,id,name,parentGroup
0,9041,European Open (DP World Tour),"{'id': 269, 'name': 'Men', 'parentGroup': {'id..."
1,54,French Open Women Doubles,"{'id': 55, 'name': 'WTA', 'parentGroup': {'id'..."
2,54,French Open Women Doubles,"{'id': 55, 'name': 'WTA', 'parentGroup': {'id'..."
3,14,French Open Men Doubles,"{'id': 18, 'name': 'ATP', 'parentGroup': {'id'..."
4,54,French Open Women Doubles,"{'id': 55, 'name': 'WTA', 'parentGroup': {'id'..."
5,14,French Open Men Doubles,"{'id': 18, 'name': 'ATP', 'parentGroup': {'id'..."
6,4217,ATP Challenger Vicenza,"{'id': 46, 'name': 'Challenger', 'parentGroup'..."
7,2632,ITF USA 17A Doubles (W),"{'id': 106, 'name': 'ITF Women', 'parentGroup'..."
8,2170,ITF USA F11 Doubles (M),"{'id': 109, 'name': 'ITF Men', 'parentGroup': ..."
9,77,WNBA,"{'id': 62, 'name': 'USA', 'parentGroup': {'id'..."
10,3988,Int. Friendly Games (W),"{'id': 34, 'name': 'International', 'parentGro..."
11,30,MLB,"{'id': 31, 'name': 'USA', 'parentGroup': {'id'..."
12,30,MLB,"{'id': 31, 'name': 'USA', 'parentGroup': {'id'..."
13,7002,Czech Liga Pro,"{'id': 7001, 'name': 'Czech Republic', 'parent..."
14,7002,Czech Liga Pro,"{'id': 7001, 'name': 'Czech Republic', 'parent..."

In [116]:
parentGroup_df = group_df['parentGroup'].apply(pd.Series)

In [117]:
parentGroup_df

      id            name                          parentGroup
0    269             Men          {'id': 270, 'name': 'Golf'}
1     55             WTA         {'id': 21, 'name': 'Tennis'}
2     55             WTA         {'id': 21, 'name': 'Tennis'}
3     18             ATP         {'id': 21, 'name': 'Tennis'}
4     55             WTA         {'id': 21, 'name': 'Tennis'}
5     18             ATP         {'id': 21, 'name': 'Tennis'}
6     46      Challenger         {'id': 21, 'name': 'Tennis'}
7    106       ITF Women         {'id': 21, 'name': 'Tennis'}
8    109         ITF Men         {'id': 21, 'name': 'Tennis'}
9     62             USA     {'id': 39, 'name': 'Basketball'}
10    34   International         {'id': 11, 'name': 'Soccer'}
11    31             USA       {'id': 32, 'name': 'Baseball'}
12    31             USA       {'id': 32, 'name': 'Baseball'}
13  7001  Czech Republic  {'id': 535, 'name': 'Table Tennis'}
14  7001  Czech Republic  {'id': 535, 'name': 'Table Tennis'}

In [118]:
parentGroup_hard_df = parentGroup_df['parentGroup'].apply(pd.Series)

In [119]:
parentGroup_hard_df

     id          name
0   270          Golf
1    21        Tennis
2    21        Tennis
3    21        Tennis
4    21        Tennis
5    21        Tennis
6    21        Tennis
7    21        Tennis
8    21        Tennis
9    39    Basketball
10   11        Soccer
11   32      Baseball
12   32      Baseball
13  535  Table Tennis
14  535  Table Tennis

In [120]:
df["markets"]

0     [{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666'...
1     [{'id': 'a85a5cf8-6f94-3d07-baa4-d44f48fc0e9d'...
2     [{'id': 'c094645a-d6d3-3c59-bed9-0a0449f146b4'...
3     [{'id': 'a2ca142e-3dd2-3090-9c13-35807223bcc3'...
4     [{'id': 'a9bcf7d2-3489-3135-b0d6-a39c20246b59'...
5     [{'id': 'a8ba9e2f-a1a8-3aaa-8497-8c8eaf288718'...
6     [{'id': 'f393e1b9-39c6-3374-ab01-626366f287f3'...
7     [{'id': '71eb97e2-8178-386d-b910-95d32b0ee461'...
8     [{'id': '2bda429d-945c-31f7-98d4-a3821e16eb0b'...
9     [{'id': 'df4c4877-9208-387b-91f1-1f8f366e0541'...
10    [{'id': '22a3d197-d423-3e12-9042-dc3ed6c9d709'...
11    [{'id': '0f9bf9d3-8684-37c7-825f-96edeb1bf655'...
12    [{'id': '04e1eeb9-2b6c-3c46-896c-2ada136f40f3'...
13    [{'id': 'dbad609d-1c31-35d8-a5ca-d2bd99c375f4'...
14    [{'id': '18da78cf-77e2-3a21-a89d-c90b9f3a0ceb'...
Name: markets, dtype: object

In [121]:
markets_df = df['markets'].apply(pd.Series)

In [122]:
markets_df

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,"{'id': 'd4243018-4867-35ac-8da2-e0c8ed9d2666',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"{'id': 'a85a5cf8-6f94-3d07-baa4-d44f48fc0e9d',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"{'id': 'c094645a-d6d3-3c59-bed9-0a0449f146b4',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"{'id': 'a2ca142e-3dd2-3090-9c13-35807223bcc3',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"{'id': 'a9bcf7d2-3489-3135-b0d6-a39c20246b59',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,"{'id': 'a8ba9e2f-a1a8-3aaa-8497-8c8eaf288718',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,"{'id': 'f393e1b9-39c6-3374-ab01-626366f287f3',...","{'id': '4bac54cf-90ba-3b83-bb5d-fb0751aa8737',...","{'id': '670597b6-cdbe-33dd-8bc2-656566890bb4',...","{'id': '029c410a-d29c-3dc2-aee2-3a9bd2faedc5',...","{'id': '654f4b44-9c4e-3f99-ae89-fcc72babfbf9',...","{'id': '7a9dc655-b17a-30c8-b994-5ad002fea7ab',...","{'id': '83488454-55b0-3377-bed1-652f5567b780',...","{'id': '2f1c338e-a256-3571-8b58-02b60f06204e',...","{'id': '26ea0127-a51f-335c-acfb-31f6c61385ea',...","{'id': '25c9b17d-55f2-3d0a-9412-18dff784cb43',...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,"{'id': '71eb97e2-8178-386d-b910-95d32b0ee461',...","{'id': '372a7230-3896-3d4a-943b-854df4590a72',...","{'id': '41115fed-441a-38e6-be9c-cd3ad9692db7',...","{'id': '73da3772-dc45-3e15-8b4c-5e53738bb481',...","{'id': 'fcaf771f-0a0e-3fa9-bae7-f40467b2491d',...","{'id': 'cf93faef-6e44-3784-8c07-7fb4e9b40afb',...","{'id': '123b9cb6-6a99-3603-964c-5840cb2f33d6',...","{'id': 'ce9495bf-d9e3-37c1-968b-5544d33acb5e',...","{'id': 'a568523e-d97b-3844-a2ef-7aeaa5e98b8f',...","{'id': 'eb83ed81-c604-39ed-a8d8-fb9544321670',...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,"{'id': '2bda429d-945c-31f7-98d4-a3821e16eb0b',...","{'id': '203a91fd-4cb4-3615-a08c-9c67928d4c20',...","{'id': '2568429a-a110-3807-8c88-d380384a5600',...","{'id': 'c3263e98-6c63-3cbe-adcb-d683fcc7a747',...","{'id': '46120183-cdbd-3d49-8d7a-7dcc27aa6966',...","{'id': 'c83707ff-15fd-36e1-819a-89039dd2e79e',...","{'id': 'b70d2714-99fa-3576-9c7b-d3c6ca735f9c',...","{'id': '32bfbc71-7ab0-3008-b614-d9835001ccaa',...","{'id': '099f73e0-a5f0-31a8-9637-39acdbf80fc4',...","{'id': 'de393085-ad2d-35c7-bb82-68253d97ac78',...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,"{'id': 'df4c4877-9208-387b-91f1-1f8f366e0541',...","{'id': '9250d9a1-bc84-3f42-b789-b2e569e54110',...","{'id': 'bd3a4f8e-5f52-3735-9ab4-79917daa5b5b',...","{'id': '383c8126-2432-3fc9-9baf-4305fbcbaf4c',...","{'id': '9283dd62-fb50-39e7-8977-d23f4380a1ac',...","{'id': 'c3a7a0a8-21a3-3b23-bcc4-6c38a91927fb',...","{'id': '15c75132-264a-37cd-97db-c4f858f869b4',...","{'id': '46188b51-b15d-3cb3-beb2-417e11423396',...","{'id': '77c72a49-6f91-3b75-9c3d-12cc85548bc4',...","{'id': 'df995201-dd5a-3f4b-b6a2-dce5d016372a',...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,"{'id': '22a3d197-d423-3e12-9042-dc3ed6c9d709',...","{'id': 'db827445-f734-384c-bd50-5ae5a5c06d3c',...","{'id': '9edaa718-21b5-3d85-b619-6cf51922eaf0',...","{'id': 'f4c2e44c-972c-3bed-b0d5-43122e997797',...","{'id': '1b56ba0a-e111-3ba3-a5dc-e50eff7665c6',...","{'id': '61d1fb7c-5a38-36f4-b61a-45af2da7ca05',...","{'id': 'ec45c889-721e-3958-9922-c1730595500c',...","{'id': '1ab3e766-a780-3a90-9ebf-44afb727e2de',...","{'id': 'ea4c8c6f-bc22-3323-8ede-06a6ff752413',...","{'id': 'cb5c000b-c4d4-3745-bcaa-95406083d645',...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,"{'id': '0f9bf9d3-8684-37c7-825f-96edeb1bf655',...","{'id': '06817649-67a3-38d3-befd-2226919a7288',...","{'id': 'a6846463-7215-3e1c-a076-ce947c1cd758',...","{'id': '0381cb3d-cd38-346d-bb2c-eb8470664bbe',...","{'id': 'f9d21674-217e-3600-99ed-49305c8d08d0',...","{'id': '9760d9da-2207-3647-aaa9-fa300d6f3b01',...","{'id': 'd2096658-a233-3d5e-bdcf-27adc1bcce73',...","{'id': 'bb2c993a-fd7e-3b53-bd54-d3244e6b3949',...","{'id': 'cb852931-3dea-34cd-a952-aa2da5ecde36',...","{'id': 'deea0cdd-afd8-3d91-a84c-cbbb54bb94eb',...",...,"{'id': 'bfc7662f-1060-345b-adb6-f2994de29eef',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,"{'id': '04e1eeb9-2b6c-3c46-896c-2ada136f40f3',...","{'id': 'f733769c-0eba-39f4-8f7c-5d7661ad0502',...","{'id': 'ce4939f7-78a5-3cff-9cf3-83ede2399db7',...","{'id': '2dc1ba10-5a11-3a89-99af-06b50ea44bdb',...","{'id': '9cc57193-c879-3751-a37d-592261ec7c44',...","{'id': 'a2e608fc-dabe-39f4-84de-221db568eeaf',...","{'id': '5b4683f2-8bdf-391c-8054-3161940f365d',...","{'id': '0ce42224-0237-3838-8956-69ee9a567823',...","{'id': '4eaa4f13-1119-31ed-bdea-9b584ba72a3c',...","{'id': '2da84bc7-9858-339e-ae9f-37f800c9ca90',...",...,"{'id': '75b81e3a-e423-3cd9-a43c-8ad32c190af5',...","{'id': '3b149f47-2a46-3fb2-b9dc-abc6bf29de4e',...","{'id': '879a65b1-06ee-3050-9d89-534a96eed3a5',...","{'id': 'a5d58260-5f92-3354-a2b6-3b5e8479a154',...","{'id': 'c26d03b8-970d-32de-9866-d425a8bdb851',...","{'id': '5b173453-967c-3cfd-9c43-54f8161d9429',...","{'id': '8d6f0b53-d1d7-3865-acca-a9fa8e4f4fcf',...","{'id': 'acc6a96c-9557-36f5-a9f6-c7ca1a4275d8',...","{'id': '5d9b974e-ad1e-3fac-81ab-f6245a7a3ceb',...","{'id': 'd3fc78ed-a868-3725-a5de-56c83a964320',..."
13,"{'id': 'dbad609d-1c31-35d8-a5ca-d2bd99c375f4',...","{'id': 'eb927a19-c926-36b9-b709-65e003f08ff1',...","{'id': 'eb33b82e-2d59-3847-b49e-9996e78fd4d3',...","{'id': '869ed9ca-bbe8-3dc6-9843-456b38b132f7',...","{'id': '7bb95793-c62e-3d34-b3e5-6d84bbd9f147',...","{'id': 'f9db284a-245f-3462-97cf-0ebf477b67b3',...","{'id': 'd356bce6-03eb-30e2-b76e-7d9b647d2057',...","{'id': '0e2ee388-719d-3cd3-a517-3a7937a88f8e',...","{'id': '2da0a8f2-7a60-3440-bfc9-ecce30bd3884',...","{'id': '7dec58d5-cdea-3601-bdb5-587d2c819e68',...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,"{'id': '18da78cf-77e2-3a21-a89d-c90b9f3a0ceb',...","{'id': 'e4e33da6-7d62-32c2-b4b6-1232c7feed6f',...","{'id': 'c99da3a5-8241-3fbe-9dfc-6cd548da59f1',...","{'id': '878e7b71-ba0c-3280-8670-9755850f1503',...","{'id': '8fc33a63-3fbe-393b-be16-c3ee39edaa5d',...","{'id': '223e0ff4-254f-34c6-93de-44491fe97059',...","{'id': 'f8c76845-4c90-326d-baea-8167f92d4990',...","{'id': '02a64e0b-2fc6-3d48-82bd-e3c185a9ac85',...","{'id': '5e8dc370-c67b-34aa-ba72-15a38b4f6c9f',...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [123]:
markets_eachone_df = markets_df[0].apply(pd.Series)

In [124]:
markets_eachone_df

,id,name,type,parameters,status,mostBalancedLine,sgpEligable,outcomes,specifier
0,d4243018-4867-35ac-8da2-e0c8ed9d2666,Tournament Winner,winner,[],BLOCKED,False,False,[{'id': 'c9eef81b-dd18-3077-bba8-2c3106661df7'...,NaN
1,a85a5cf8-6f94-3d07-baa4-d44f48fc0e9d,Moneyline,standard,[],OPEN,True,False,[{'id': '047fad12-af4d-397a-bb30-e42ba15c96b6'...,NaN
2,c094645a-d6d3-3c59-bed9-0a0449f146b4,Moneyline,standard,[],OPEN,True,False,[{'id': 'bcd947df-7613-36b5-9342-9b1973387538'...,NaN
3,a2ca142e-3dd2-3090-9c13-35807223bcc3,Moneyline,standard,[],OPEN,True,False,[{'id': '82c979ab-e589-3073-9497-03e5a1a1552d'...,NaN
4,a9bcf7d2-3489-3135-b0d6-a39c20246b59,Moneyline,standard,[],OPEN,False,False,[{'id': 'e2b2afaf-dff9-3951-a3e1-1bde962e6f1d'...,NaN
5,a8ba9e2f-a1a8-3aaa-8497-8c8eaf288718,Moneyline,standard,[],OPEN,True,False,[{'id': '625dedae-013d-30dd-be03-7e4d1cc81819'...,NaN
6,f393e1b9-39c6-3374-ab01-626366f287f3,2nd Set 7th Game 4th Point Winner,exact-game-point-in-set,"[2, 7, 4]",OPEN,False,False,[{'id': 'ca7f4c36-d008-3153-bbc8-f1ab24de6e52'...,"[{'key': 'SECTION', 'value': '2', 'type': 'LON..."
7,71eb97e2-8178-386d-b910-95d32b0ee461,Codd K / Tse E To Win Exactly One Set,away-to-win-exactly-one-set,[],OPEN,False,False,[{'id': 'ccb2cabd-e55b-31ff-8af5-51bbb2151342'...,NaN
8,2bda429d-945c-31f7-98d4-a3821e16eb0b,Ayeni O A D / Azkara A To Win A Set,away-to-win-a-set,[],OPEN,False,False,[{'id': '1c8772fe-3ed8-3038-b384-ed898e2af3e7'...,NaN
9,df4c4877-9208-387b-91f1-1f8f366e0541,1st Half Winner,first-half-draw-no-bet,[],OPEN,True,False,[{'id': 'ef0d9c02-cc6d-307a-b052-154d3706b138'...,NaN
10,22a3d197-d423-3e12-9042-dc3ed6c9d709,Correct Score,correct-score-live,[],OPEN,False,True,[{'id': 'aaa18cb3-1be7-3d1d-8c46-e446ae0a0bb5'...,NaN
11,0f9bf9d3-8684-37c7-825f-96edeb1bf655,Diamondbacks Total Hits,away-total-hits-include-extra-innings,[5.5],OPEN,False,False,[{'id': '0b7e9e35-1ab6-382f-8c18-fa0865301e7e'...,"[{'key': 'OVER_UNDER', 'value': '5.5', 'type':..."
12,04e1eeb9-2b6c-3c46-896c-2ada136f40f3,Nationals Total Hits,away-total-hits-include-extra-innings,[7.5],OPEN,False,False,[{'id': '839a1e45-faab-3921-93d4-59e16a23c97e'...,"[{'key': 'OVER_UNDER', 'value': '7.5', 'type':..."
13,dbad609d-1c31-35d8-a5ca-d2bd99c375f4,Total Points Spread,game-handicap,"[0, 0.5]",OPEN,True,False,[{'id': '404cbf3d-dccd-3701-baa7-61b5c7e26b32'...,"[{'key': 'HANDICAP_HOME', 'value': '0', 'type'..."
14,18da78cf-77e2-3a21-a89d-c90b9f3a0ceb,Total Points Spread,game-handicap,"[0, 6.5]",OPEN,True,False,[{'id': 'c012c95b-a962-3713-a6e2-5a85f780b402'...,"[{'key': 'HANDICAP_HOME', 'value': '0', 'type'..."

In [125]:
market_outcome_df = markets_eachone_df['outcomes'].apply(pd.Series)

In [126]:
market_outcome_df

,0,1,2,3,4,5,6,7,8,9,...,137,138,139,140,141,142,143,144,145,146
0,"{'id': 'c9eef81b-dd18-3077-bba8-2c3106661df7',...","{'id': '5ffde8f9-fa13-39a3-b221-469ef3fae2db',...","{'id': 'e53af6fa-7048-3c6c-bd83-dc1dd1855a31',...","{'id': '863e0a64-0424-3092-a4aa-bc4e9f047dfe',...","{'id': '898b68d1-375e-35aa-bf54-a4bc1cbe21be',...","{'id': '7a6be19e-d3e6-3a6b-b221-b52c542c82fc',...","{'id': 'b5500ecb-1c06-3ff2-969b-a2f8a1587426',...","{'id': '61ef2909-fcd1-371d-9768-9f7997bc48a2',...","{'id': '3934ea97-b714-37fc-bc46-a02c564e5985',...","{'id': 'e2bb26e0-cfa0-388e-bb96-4c2c49a88a88',...",...,"{'id': '2eb4eafa-e077-30a8-9a15-54e46aace5df',...","{'id': '2c13a415-ed1f-3bff-9846-a9f973496318',...","{'id': 'fafe5b88-56d0-34ff-8353-e91325442935',...","{'id': '92af17ae-8a1a-3877-8fce-ab449eb90fcb',...","{'id': '6615ff71-d2ec-3f69-8647-55e5cb3d6ab1',...","{'id': '762acab4-f83a-3aa0-9821-d4543a6e8038',...","{'id': 'b2f1efa5-ee26-392a-bac3-f97997ec8552',...","{'id': '77508f38-1003-322c-b52b-7453766aabf3',...","{'id': '996b4df4-7db4-35ba-b150-098078d2c803',...","{'id': '8c9b72e3-64ad-3176-9a75-0efa4e76b6b3',..."
1,"{'id': '047fad12-af4d-397a-bb30-e42ba15c96b6',...","{'id': '0fe14f6a-3c54-3be6-a01f-bb25cac87ede',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"{'id': 'bcd947df-7613-36b5-9342-9b1973387538',...","{'id': '5c51d455-41c3-3de3-a408-1c9eb85f67f9',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"{'id': '82c979ab-e589-3073-9497-03e5a1a1552d',...","{'id': 'c53d3a60-7e6c-3b63-991b-4e807d229a20',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"{'id': 'e2b2afaf-dff9-3951-a3e1-1bde962e6f1d',...","{'id': 'd4206670-7896-3aed-8cfc-c0e05e59b32d',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,"{'id': '625dedae-013d-30dd-be03-7e4d1cc81819',...","{'id': 'ce3ac191-1cef-31aa-85e9-643638738d77',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,"{'id': 'ca7f4c36-d008-3153-bbc8-f1ab24de6e52',...","{'id': 'f3b178ab-bb95-3a46-8d95-4a7d54e99ca5',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,"{'id': 'ccb2cabd-e55b-31ff-8af5-51bbb2151342',...","{'id': 'a4cbb855-8b6c-325c-999b-1186f5ed05d9',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,"{'id': '1c8772fe-3ed8-3038-b384-ed898e2af3e7',...","{'id': 'bd9d8c01-68bb-3934-9d70-8a0f5226d4f1',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,"{'id': 'ef0d9c02-cc6d-307a-b052-154d3706b138',...","{'id': 'ecf5c1d3-4088-3347-a0c0-50aec8685339',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,"{'id': 'aaa18cb3-1be7-3d1d-8c46-e446ae0a0bb5',...","{'id': 'b45d9164-9a7a-39ad-8b49-35eff9fe1c64',...","{'id': 'c6d890b4-4c93-35f1-b727-5d33aa9f1515',...","{'id': 'f8eec925-593b-33eb-9726-faa4c4b124a2',...","{'id': '056e1ff8-bd6f-3809-b7a8-688a24392110',...","{'id': 'f198b3dc-a2f3-39f7-80c3-3164aa073e08',...","{'id': '8927202e-1230-37df-a524-7ace4c517ff9',...","{'id': '82054c06-d42e-379a-8739-b0d123c13a77',...","{'id': 'ca9c80c1-6630-3a3c-8e69-10131c978f36',...","{'id': 'c562877d-4604-3f94-8123-043420ff55d1',...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,"{'id': '0b7e9e35-1ab6-382f-8c18-fa0865301e7e',...","{'id': 'a361405c-a712-3158-9d29-6e2edad6fce3',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,"{'id': '839a1e45-faab-3921-93d4-59e16a23c97e',...","{'id': '58e76bfe-4594-3284-bdeb-738e83b97cf2',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,"{'id': '404cbf3d-dccd-3701-baa7-61b5c7e26b32',...","{'id': '3fa4b34a-ad4b-3391-996d-0a2059764c99',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,"{'id': 'c012c95b-a962-3713-a6e2-5a85f780b402',...","{'id': 'f04ac8af-db15-3f04-b622-77b9fb3b21db',...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [127]:
market_outcome_eachone_df = market_outcome_df[0].apply(pd.Series)

In [128]:
market_outcome_eachone_df

,id,name,isTraded,formatDecimal,formatAmerican,status,trueOdds
0,c9eef81b-dd18-3077-bba8-2c3106661df7,"Canter, Laurie",True,6.50,550,ONGOING,6.500000
1,047fad12-af4d-397a-bb30-e42ba15c96b6,Kato M / Kichenok N,True,1.17,-556,ONGOING,1.179856
2,bcd947df-7613-36b5-9342-9b1973387538,Jacquemot E / Tan H,True,4.60,360,ONGOING,4.600000
3,82c979ab-e589-3073-9497-03e5a1a1552d,Johnson L / Mansouri S,True,1.10,-1000,ONGOING,1.100000
4,e2b2afaf-dff9-3951-a3e1-1bde962e6f1d,Dolehide CA / Krawczyk D,False,1.03,-3333,ONGOING,1.030003
5,625dedae-013d-30dd-be03-7e4d1cc81819,Koolhof W / Mektic N,True,1.09,-1111,ONGOING,1.090009
6,ca7f4c36-d008-3153-bbc8-f1ab24de6e52,"Dellien Velasco, Murkel Alejandro",True,1.93,-107,ONGOING,1.934579
7,ccb2cabd-e55b-31ff-8af5-51bbb2151342,Yes,True,5.20,420,ONGOING,5.200000
8,1c8772fe-3ed8-3038-b384-ed898e2af3e7,Yes,True,5.70,470,ONGOING,5.700000
9,ef0d9c02-cc6d-307a-b052-154d3706b138,Fever,True,7.70,670,ONGOING,7.700000
10,aaa18cb3-1be7-3d1d-8c46-e446ae0a0bb5,0-0,True,3.70,270,ONGOING,3.700000
11,0b7e9e35-1ab6-382f-8c18-fa0865301e7e,Over 5.5,True,1.42,-238,ONGOING,1.420168
12,839a1e45-faab-3921-93d4-59e16a23c97e,Over 7.5,True,1.64,-154,ONGOING,1.649351
13,404cbf3d-dccd-3701-baa7-61b5c7e26b32,"Zatecka, Ladislav -0.5",True,1.84,-118,ONGOING,1.847458
14,c012c95b-a962-3713-a6e2-5a85f780b402,"Sychra, Martin -6.5",True,1.90,-111,ONGOING,1.900901

In [129]:
market_specifiers_df = markets_eachone_df['specifier'].apply(pd.Series)

In [130]:
market_specifiers_df

,0,1,2
0,NaN,NaN,NaN
1,NaN,NaN,NaN
2,NaN,NaN,NaN
3,NaN,NaN,NaN
4,NaN,NaN,NaN
5,NaN,NaN,NaN
6,"{'key': 'SECTION', 'value': '2', 'type': 'LONG'}","{'key': 'SUBSECTION', 'value': '7', 'type': 'L...","{'key': 'POINT_NUMBER', 'value': '4', 'type': ..."
7,NaN,NaN,NaN
8,NaN,NaN,NaN
9,NaN,NaN,NaN
10,NaN,NaN,NaN
11,"{'key': 'OVER_UNDER', 'value': '5.5', 'type': ...",NaN,NaN
12,"{'key': 'OVER_UNDER', 'value': '7.5', 'type': ...",NaN,NaN
13,"{'key': 'HANDICAP_HOME', 'value': '0', 'type':...","{'key': 'HANDICAP_AWAY', 'value': '0.5', 'type...",NaN
14,"{'key': 'HANDICAP_HOME', 'value': '0', 'type':...","{'key': 'HANDICAP_AWAY', 'value': '6.5', 'type...",NaN

In [131]:
market_specifiers_eachone_df = market_specifiers_df[0].apply(pd.Series)

In [132]:
market_specifiers_eachone_df

     0            key value    type
0  NaN            NaN   NaN     NaN
1  NaN            NaN   NaN     NaN
2  NaN            NaN   NaN     NaN
3  NaN            NaN   NaN     NaN
4  NaN            NaN   NaN     NaN
5  NaN            NaN   NaN     NaN
6  NaN        SECTION     2    LONG
7  NaN            NaN   NaN     NaN
8  NaN            NaN   NaN     NaN
9  NaN            NaN   NaN     NaN
10 NaN            NaN   NaN     NaN
11 NaN     OVER_UNDER   5.5  DOUBLE
12 NaN     OVER_UNDER   7.5  DOUBLE
13 NaN  HANDICAP_HOME     0  DOUBLE
14 NaN  HANDICAP_HOME     0  DOUBLE

In [133]:
df['eventDetails']

0     {'block_cashout': 'false', 'longTermEventType'...
1     {'subgroupNameKey': 'French Open Women Doubles...
2     {'subgroupNameKey': 'French Open Women Doubles...
3     {'subgroupNameKey': 'French Open Men Doubles, ...
4     {'subgroupNameKey': 'French Open Women Doubles...
5     {'subgroupNameKey': 'French Open Men Doubles, ...
6     {'subgroupNameKey': 'ATP Challenger Vicenza, I...
7     {'subgroupNameKey': 'ITF USA 17A, Women Double...
8     {'subgroupNameKey': 'ITF USA F11, Men Doubles,...
9     {'subgroupNameKey': 'WNBA, Western Conference'...
10    {'subgroupNameKey': 'International Friendly Ga...
11    {'subgroupNameKey': 'MLB, National League West...
12    {'subgroupNameKey': 'MLB, National League East...
13    {'subgroupNameKey': 'Czech Liga Pro', 'best_of...
14    {'subgroupNameKey': 'Czech Liga Pro', 'best_of...
Name: eventDetails, dtype: object

In [134]:
eventDetails_df = df['eventDetails'].apply(pd.Series)

In [135]:
eventDetails_df

,block_cashout,longTermEventType,outrightType,subgroupNameKey,best_of_sets,activeParticipant,subgroupIdKey,tiebreak,home_pitcher,away_pitcher
0,false,COMPETITION_GROUP,stage,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,false,NaN,NaN,"French Open Women Doubles, Round_of_64",3,HOME,141672,NaN,NaN,NaN
2,false,NaN,NaN,"French Open Women Doubles, Round_of_64",3,AWAY,141672,NaN,NaN,NaN
3,false,NaN,NaN,"French Open Men Doubles, Round_of_64",3,HOME,139440,NaN,NaN,NaN
4,false,NaN,NaN,"French Open Women Doubles, Round_of_64",3,HOME,141672,NaN,NaN,NaN
5,false,NaN,NaN,"French Open Men Doubles, Round_of_64",3,HOME,139440,NaN,NaN,NaN
6,false,NaN,NaN,"ATP Challenger Vicenza, Italy Men Singles, Rou...",3,AWAY,147401,NaN,NaN,NaN
7,false,NaN,NaN,"ITF USA 17A, Women Doubles, Quarterfinal",3,HOME,150063,immediate-tie-break,NaN,NaN
8,false,NaN,NaN,"ITF USA F11, Men Doubles, Quarterfinal",3,AWAY,149991,immediate-tie-break,NaN,NaN
9,false,NaN,NaN,"WNBA, Western Conference",NaN,NaN,591,NaN,NaN,NaN
10,false,NaN,NaN,"International Friendly Games, Women",NaN,NaN,1039,NaN,NaN,NaN
11,false,NaN,NaN,"MLB, National League West",NaN,NaN,25,NaN,Christian Scott,Zac Gallen
12,false,NaN,NaN,"MLB, National League East",NaN,NaN,25,NaN,Raymond Kerr,Trevor Williams
13,false,NaN,NaN,Czech Liga Pro,5,NaN,93955,NaN,NaN,NaN
14,false,NaN,NaN,Czech Liga Pro,5,NaN,93955,NaN,NaN,NaN

In [22]:
participant_temp_df = participants_df[1].apply(pd.Series)
#participant_temp_df['match_id'] = df['id']

KeyError: 1

In [42]:
participants_df

,0,1
0,"{'id': 85914, 'name': 'Hinojosa Gomez J / Reas...","{'id': 85913, 'name': 'Bozovic A / Wong H Y C'..."
1,"{'id': 557, 'name': 'Djere, Laslo', 'position'...","{'id': 579, 'name': 'Altmaier, Daniel', 'posit..."
2,"{'id': 204, 'name': 'White Sox', 'position': '...","{'id': 214, 'name': 'Orioles', 'position': 'AW..."
3,"{'id': 1099, 'name': 'Panthers', 'position': '...","{'id': 1105, 'name': 'Rangers', 'position': 'A..."
4,"{'id': 55190, 'name': 'San Jose State', 'posit...","{'id': 55049, 'name': 'Fresno State ', 'positi..."
5,"{'id': 228, 'name': 'Angels', 'position': 'HOM...","{'id': 206, 'name': 'Guardians', 'position': '..."
6,"{'id': 24, 'name': 'Athletics', 'position': 'H...","{'id': 26, 'name': 'Astros', 'position': 'AWAY..."
7,"{'id': 85773, 'name': 'Padres', 'position': 'H...","{'id': 17350, 'name': 'Yankees', 'position': '..."
8,"{'id': 256, 'name': 'Diamondbacks', 'position'...","{'id': 241, 'name': 'Marlins', 'position': 'AW..."
9,"{'id': 9402, 'name': 'CA Sarmiento', 'position...","{'id': 31762, 'name': 'Independiente Rivadavia..."
10,"{'id': 35333, 'name': 'Racing de Cordoba', 'po...","{'id': 10293, 'name': 'San Martin de Tucuman',..."
11,"{'id': 36889, 'name': 'CD El Nacional', 'posit...","{'id': 34634, 'name': 'Mushuc Runa SC', 'posit..."
12,"{'id': 31731, 'name': 'Deportivo Maldonado', '...","{'id': 32042, 'name': 'Atletico Fenix Montevid..."
13,"{'id': 2713, 'name': 'Gimnasia Y Esgrima La Pl...","{'id': 2724, 'name': 'CA Banfield', 'position'..."
14,"{'id': 2958, 'name': 'Kirchheimer, Strong', 'p...","{'id': 16039, 'name': 'Nefve, Axel', 'position..."
15,"{'id': 2903, 'name': 'Langmo, Christian', 'pos...","{'id': 39396, 'name': 'Kumar, Pranav', 'positi..."
16,"{'id': 4853, 'name': 'Universidad de Chile', '...","{'id': 20598, 'name': 'Nublense', 'position': ..."
17,"{'id': 1171, 'name': 'Ceara SC CE', 'position'...","{'id': 14, 'name': 'Chapecoense SC', 'position..."

In [56]:
participants_df = pd.concat([participants_eachone_df, participant_temp_df], ignore_index=True)

In [57]:
participants_df

,id,name,position,abbreviation,match_id
0,85914,Hinojosa Gomez J / Reasco Gonzalez M E,HOME,HRE,815139
1,557,"Djere, Laslo",HOME,DJE,812878
2,204,White Sox,HOME,CWS,814260
3,1099,Panthers,HOME,FLA,807148
4,55190,San Jose State,HOME,SAN,814658
5,228,Angels,HOME,LAA,814281
6,24,Athletics,HOME,OAK,814282
7,85773,Padres,HOME,SD,814280
8,256,Diamondbacks,HOME,ARI,814296
9,9402,CA Sarmiento,HOME,CAS,809278
10,35333,Racing de Cordoba,HOME,RAC,809872
11,36889,CD El Nacional,HOME,ELN,811400
12,31731,Deportivo Maldonado,HOME,MAL,809579
13,2713,Gimnasia Y Esgrima La Plata,HOME,GLP,808810
14,2958,"Kirchheimer, Strong",HOME,KIR,814471
15,2903,"Langmo, Christian",HOME,LAN,814472
16,4853,Universidad de Chile,HOME,UCH,809021
17,1171,Ceara SC CE,HOME,CEA,809052
18,85913,Bozovic A / Wong H Y C,AWAY,BWO,815139
19,579,"Altmaier, Daniel",AWAY,ALT,812878
20,214,Orioles,AWAY,BAL,814260
21,1105,Rangers,AWAY,NYR,807148
22,55049,Fresno State,AWAY,FRB,814658
23,206,Guardians,AWAY,CLE,814281
24,26,Astros,AWAY,HOU,814282
25,17350,Yankees,AWAY,NYY,814280
26,241,Marlins,AWAY,MIA,814296
27,31762,Independiente Rivadavia,AWAY,IRM,809278
28,10293,San Martin de Tucuman,AWAY,SMT,809872
29,34634,Mushuc Runa SC,AWAY,MUR,811400
30,32042,Atletico Fenix Montevideo,AWAY,FEN,809579
31,2724,CA Banfield,AWAY,BAN,808810
32,16039,"Nefve, Axel",AWAY,NEF,814471
33,39396,"Kumar, Pranav",AWAY,KUM,814472
34,20598,Nublense,AWAY,NUB,809021
35,14,Chapecoense SC,AWAY,CHA,809052

In [34]:
df

,id,startTime,messageTime,sportType,matchState,participants,status,marketCount,group,markets,...,displayInfo,score,gameClock,eventReferences,eventDetails,sportCurrentGameState,lastModifiedTime,eventTags,aggregatedEventPoints,eventMetadata
0,815139,2024-05-26T14:00:00Z,2024-05-26T22:09:24.236Z,TENNIS,ONGOING,"[{'id': 85914, 'name': 'Hinojosa Gomez J / Rea...",RUNNING,25,"{'id': 3434, 'name': 'ITF Dominican Republic 0...",[{'id': '759e6bee-19c9-3f0e-a4d4-0cb8d121eaab'...,...,{},"{'total': {'home': {'sets': 1, 'games': 1, 'po...","{'clockType': 'SECTIONS', 'eventState': 'RUNNI...","[{'providerId': '90', 'eventId': '50352659'}, ...",{'subgroupNameKey': 'ITF Dominican Republic 03...,"{'updatedAt': '0', 'netSportCurrentGameState':...",2024-05-26T22:09:24.366Z,"[awayParticipantStateLocation:UNKNOWN, venueSt...",NaN,NaN
1,812878,2024-05-26T17:50:00Z,2024-05-26T22:08:58.023Z,TENNIS,ONGOING,"[{'id': 557, 'name': 'Djere, Laslo', 'position...",RUNNING,23,"{'id': 51, 'name': 'French Open Men', 'parentG...",[{'id': '5e59f74c-a2cc-377d-93a8-c047d9d96385'...,...,{},"{'total': {'home': {'sets': 2, 'games': 3, 'po...","{'clockType': 'SECTIONS', 'eventState': 'RUNNI...","[{'providerId': '81', 'eventId': '535209659452...","{'subgroupNameKey': 'French Open Men Singles, ...","{'updatedAt': '0', 'netSportCurrentGameState':...",2024-05-26T22:08:58.168Z,"[awayParticipantStateLocation:OTHER, venueStat...",NaN,NaN
2,814260,2024-05-26T18:10:00Z,2024-05-26T22:09:38.382Z,BASEBALL,ONGOING,"[{'id': 204, 'name': 'White Sox', 'position': ...",RUNNING,3,"{'id': 30, 'name': 'MLB', 'parentGroup': {'id'...",[{'id': '4deba7ae-426d-38b5-865c-a18597fcd38c'...,...,{},"{'total': {'home': {'value': 1}, 'away': {'val...","{'clockType': 'SECTIONS', 'eventState': 'RUNNI...","[{'providerId': '49', 'eventId': '23045'}, {'p...","{'subgroupNameKey': 'MLB, American League East...","{'updatedAt': '1716761368404', 'baseballCurren...",2024-05-26T22:09:38.553Z,"[homeParticipantStateLocation:US-IL, venueStat...",NaN,NaN
3,807148,2024-05-26T19:00:00Z,2024-05-26T22:09:05.952Z,ICE_HOCKEY,ONGOING,"[{'id': 1099, 'name': 'Panthers', 'position': ...",RUNNING,1,"{'id': 81, 'name': 'NHL', 'parentGroup': {'id'...",[{'id': '80c49585-2edc-327d-81a3-14188cc867a4'...,...,{},"{'total': {'home': {'value': 4}, 'away': {'val...","{'clockType': 'TIMER', 'eventState': 'BREAK', ...","[{'providerId': '49', 'eventId': '23016'}, {'p...","{'subgroupNameKey': 'NHL, Eastern_conference_f...",NaN,2024-05-26T22:09:06.082Z,"[homeParticipantStateLocation:US-FL, awayParti...",NaN,NaN
4,814658,2024-05-26T20:00:00Z,2024-05-26T22:06:47.722Z,BASEBALL,ONGOING,"[{'id': 55190, 'name': 'San Jose State', 'posi...",RUNNING,1,"{'id': 3995, 'name': 'NCAABB', 'parentGroup': ...",[{'id': '5468720f-ca9e-34eb-8774-86e1522ec2cc'...,...,{'displayTags': ['sgp-pre']},"{'total': {'home': {'value': 3}, 'away': {'val...","{'clockType': 'SECTIONS', 'eventState': 'RUNNI...","[{'providerId': '84', 'eventId': '537495075733...","{'subgroupNameKey': 'Mountain West Conference,...","{'updatedAt': '1716761207464', 'baseballCurren...",2024-05-26T22:06:47.845Z,"[college, awayParticipantStateLocation:US-CA, ...",NaN,NaN
5,814281,2024-05-26T20:07:00Z,2024-05-26T22:08:43.213Z,BASEBALL,ONGOING,"[{'id': 228, 'name': 'Angels', 'position': 'HO...",RUNNING,78,"{'id': 30, 'name': 'MLB', 'parentGroup': {'id'...",[{'id': 'f46f32ec-3b9b-3176-85b1-dcd231f95d91'...,...,{},"{'total': {'home': {'value': 2}, 'away': {'val...","{'clockType': 'SECTIONS', 'eventState': 'RUNNI...","[{'providerId': '81', 'eventId': '536985841216...","{'subgroupNameKey': 'MLB, American League West...","{'updatedAt': '1716761322708', 'baseballCurren...",2024-05-26T22:08:43.402Z,"[venueStateLocation:US-CA, awayParticipantStat...",NaN,NaN
6,814282,2024-05-26T20:07:00Z,2024-05-26T22:09:32.182Z,BASEBALL,ONGOING,"[{'id': 24, 'name': 'Athletics', 'position': '...",RUNNING,50,"{'id': 30, 'name': 'MLB', 'parentGroup': {'id'...",[{'id': '274ef578-0b81-3a10-b768-5eb84a0369cf'...,...,{},"{'total': {'home': {'value': 1}, 'away': {'val...","{'clockType': 'SECTIONS', 'eventState': 'RUNNI...","[{'providerId': '81', 'eventId': '536984893482...","{'subgroupNameKey': 'MLB, American League West...","{'updatedAt': '1716761371661', 'baseballCurren...",2024-05-26T22:09:32.379Z,"[venueStateLocation:US-CA, homeParticipantStat...",NaN,NaN
7,814280,2024-05-26T20:10:00Z,2024-05-26T22:09:35.569Z,BASEBALL,ONGOING,"[{'id': 85773, 'name': 'Padres', 'position': '...",RUNNING,76,"{'id': 30, 'name': 'MLB', 'parentGroup': {'id'...",[{'id': '30730fe3-edbf-388e-898a-3bb396680199'...,...,{},"{'total': {'home': {'value': 3}, 'away': {'val...","{'clockType': 'SECTIONS', 'eventState': 'RUNNI...","[{'providerId': '81', 'eventId': '536985842024...","{'subgroupNameKey': 'MLB, National League West...","{'updatedAt': '1716761375159', 'baseballCurren...",2024-05-26T22:09:35.742Z,"[venueStateLocation:US-CA, awayParticipantStat...",NaN,NaN
8,814296,2024-05-26T20:10:00Z,2024-05-26T22:09:38.140Z,BASEBALL,ONGOING,"[{'id': 256, 'name': 'Diamondbacks', 'position...",RUNNING,80,"{'id': 30, 'name': 'MLB', 'parentGroup': {'id'...",[{'id': '7515045f-2524-3b6d-b009-c30e268abfa5'...,...,{},"{'total': {'home': {'value': 0}, 'away': {'val...","{'clockType': 'SECTIONS', 'eventState': 'RUNNI...","[{'providerId': '81', 'eventId': '536998876977...","{'subgroupNameKey': 'MLB, National League West...","{'updatedAt': '1716761377732', 'baseballCurren...",2024-05-26T22:09:38.316Z,"[homeParticipantStateLocation:US-AZ, awayParti...",NaN,NaN
9,809278,2024-05-26T20:30:00Z,2024-05-26T22:09:27.465Z,FOOTBALL,ONGOING,"[{'id': 9402, 'name': 'CA Sarmiento', 'positio...",RUNNING,17,"{'id': 1781, 'name': 'Argentina - Liga Profesi...",[{'id': '2e8b6954-2071-338d-bd40-381a7852bc13'...,...,"{'displayTags': ['sgp-pre', 'sgp-live']}","{'total': {'home': {'value': 0}, 'away': {'val...","{'clockType': 'STOPWATCH', 'eventState': 'RUNN...","[{'providerId': '81', 'eventId': '529965919598...","{'subgroupNameKey': 'Liga Profesional, Regular...",NaN,2024-05-26T22:09:27.601Z,"[sgp-pre, awayParticipantStateLocation:OTHER, ...","{'total': {'home': {'CORNER': 4, 'YELLOW_CARD'...",NaN
10,809872,2024-05-26T20:30:00Z,2024-05-26T22:09:16.890Z,FOOTBALL,ONGOING,"[{'id': 35333, 'name': 'Racing de Cordoba', 'p...",RUNNING,4,"{'id': 3686, 'name': 'Argentina - Primera Naci...",[{'id': '38616b4e-019e-3e46-8193-66d011cf3da8'...,...,"{'displayTags': ['sgp-pre', 'sgp-live']}","{'total': {'home': {'value': 0}, 'away': {'val...","{'clockType': 'STOPWATCH', 'eventState': 'RUNN...","[{'providerId': '81', 'eventId': '532662777725...","{'subgroupNameKey': 'Primera B Nacional', 'blo...",NaN,2024-05-26T22:09:17.022Z,"[sgp-pre, awayParticipantStateLocation:OTHER, ...","{'total': {'home': {'CORNER': 3, 'YELLOW_CARD'...",NaN
11,811400,2024-05-26T20:30:00Z,2024-05-26T22:09:15.346Z,FOOTBALL,ONGOING,"[{'id': 36889, 'name': 'CD El Nacional', 'posi...",RUNNING,13,"{'id': 3962, 'name': 'Ecuador - LigaPro Primer...",[{'id': '8fbdd379-e14a-33df-bc8e-815a1218c76a'...,...,"{'displayTags': ['sgp-pre', 'sgp-live']}","{'total': {'home': {'value': 1}, 'away': {'val...","{'clockType': 'STOPWATCH', 'eventState': 'RUNN...","[{'providerId': '81', 'eventId': '531715985298...","{'subgroupNameKey': 'LigaPro Primera A, Primer...",NaN,2024-05-26T22:09:15.480Z,"[sgp-pre, awayParticipantStateLocation:OTHER, ...","{'total': {'home': {'CORNER': 5, 'YELLOW_CARD'...",NaN
12,809579,2024-05-26T20:30:00Z,2024-05-26T22:09:28.687Z,FOOTBALL,ONGOING,"[{'id': 31731, 'name': 'Deportivo Maldonado', ...",RUNNING,13,"{'id': 3677, 'name': 'Uruguay - Primera Divisi...",[{'id': 'e25abef7-e47d-32db-bce1-dcb43fac1a7d'...,...,"{'displayTags': ['sgp-pre', 'sgp-live']}","{'total': {'home': {'value': 0}, 'away': {'val...","{'clockType': 'STOPWATCH', 'eventState': 'RUNN...","[{'providerId': '81', 'eventId': '531546212183...","{'subgroupNameKey': 'Primera Division, Apertur...",NaN,2024-05-26T22:09:28.822Z,"[sgp-pre, awayParticipantStateLocation:OTHER, ...","{'total': {'home': {'CORNER': 0, 'YELLOW_CARD'...",NaN
13,808810,2024-05-26T20:45:00Z,2024-05-26T22:09:14.998Z,FOOTBALL,ONGOING,"[{'id': 2713, 'name': 'Gimnasia Y Esgrima La P...",RUNNING,21,"{'id': 1781, 'name': 'Argentina - Liga Profesi...",[{'id': 'a7f0c43f-90f1-38bc-84d4-6a885565a928'...,...,"{'displayTags': ['sgp-pre', 'sgp-live']}","{'total': {'home': {'value': 0}, 'away': {'val...","{'clockType': 'STOPWATCH', 'eventState': 'RUNN...","[{'providerId': '81', 'eventId': '529969351147...","{'subgroupNameKey': 'Liga Profesional, Regular...",NaN,2024-05-26T22:09:15.134Z,"[sgp-pre, awayParticipantStateLocation:OTHER, ...","{'total': {'home': {'CORNER': 1, 'YELLOW_CARD'...",NaN
14,814471,2024-05-26T20:50:00Z,2024-05-26T22:09:32.709Z,TENNIS,ONGOING,"[{'id': 2958, 'name': 'Kirchheimer, Strong', '...",RUNNING,14,"{'id': 1549, 'name': 'ATP Challenger Little Ro...",[{'id': '3703ef72-5ab2-35f6-a7f4-761e94040012'...,...,{},"{'total': {'home': {'sets': 0, 'games': 2, 'po...","{'clockType': 'SECTIONS', 'eventState': 'RUNNI...","[{'providerId': '71', 'eventId': '11083654'}, ...",{'subgroupNameKey': 'ATP Challenger Little Roc...,"{'updatedAt': '1716761371893', 'netSportCurren...",2024-05-26T22:09:32.842Z,"[venueStateLocation:US-AR, awayParticipantStat...",NaN,{'event-widget': {'providerId': '71'}}
15,814472,2024-05-26T21:05:00Z,2024-05-26T22:09:26.035Z,TENNIS,ONGOING,"[{'id': 2903, 'name': 'Langmo, Christian', 'po...",RUNNING,13,"{'id': 1549, 'name': 'ATP Challenger Little Ro...",[{'id': 'd6b5b3f0-2efc-35d1-8321-bbf759cd7b92'...,...,{},"{'total': {'home': {'sets': 0, 'games': 1, 'po...","{'clockType': 'SECTIONS', 'eventState': 'RUNNI...","[{'providerId': '71', 'eventId': '11083656'}, ...",{'subgroupNameKey': 'ATP Challenger Little Roc...,"{'updatedAt': '1716761358839', 'netSportCurren...",2024-05-26T22:09:26.129Z,"[venueStateLocation:US-AR, awayParticipantStat...",NaN,{'event-widget': {'providerId': '71'}}
16,809021,2024-05-26T21:30:00Z,2024-05-26T22:09:23.966Z,FOOTBALL,ONGOING,"[{'id': 4853, 'name': 'Universidad de Chile', ...",RUNNING,8,"{'id': 2314, 'name': 'Chile - Primera Division...",[{'id': '589fc7dd-1249-32b2-b35c-6446e2418dfc'...,...,"{'displayTags': ['sgp-pre', 'sgp-live']}","{'total': {'home': {'value': 0}, 'away': {'val...","{'clockType': 'STOPWATCH', 'eventState': 'RUNN...","[{'providerId': '81', 'eventId': '531611963927...","{'subgroupNameKey': 'Primera Division, Regular...",NaN,2024-05-26T22:09:24.098Z,"[sgp-pre, awayParticipantStateLocation:OTHER, ...","{'total': {'home': {'CORNER': 6, 'YELLOW_CARD'...",NaN
17,809052,2024-05-26T21:30:00Z,2024-05-26T22:09:24.902Z,FOOTBALL,ONGOING,"[{'id': 1171, 'name': 'Ceara SC CE', 'position...",RUNNING,32,"{'id': 29, 'name': 'Brazil - Brasileiro Serie ...",[{'id': '616b2f60-524c-3c61-9b86-3d6fdd29ba40'...,...,"{'displayTags': ['sgp-pre', 'sgp-live']}","{'total': {'home': {'value': 0}, 'away': {'val...","{'clockType': 'STOPWATCH', 'eventState': 'RUNN...","[{'providerId': '81', 'eventId': '531618620634...","{'subgroupNameKey': 'Brasileiro Serie B, Regul...",NaN,2024-05-26T22:09:25.038Z,"[sgp-pre, awayParticipantStateLocation:OTHER, ...","{'total': {'home': {'CORNER': 1, 'YELLOW_CARD'...",NaN

In [35]:
filename = f'data/tipico_data_{datetime.now().strftime("%Y%m%d%H%M%S")}.csv'

In [36]:
df.to_csv(filename)